include("${PROJECT_SOURCE_DIR}/cmake/Testing.cmake")

if(CMAKE_CROSSCOMPILING)
  add_subdirectory(tc002/arm)
  return()
endif()
include("${PROJECT_SOURCE_DIR}/cmake/Unity.cmake")
add_subdirectory(host)
add_subdirectory(mqtt_parser)
add_subdirectory(linux)
add_subdirectory(layout)
add_subdirectory(bootintro)
add_subdirectory(update)
add_subdirectory(tc002)
add_subdirectory(tools)
