#pragma once
// GENERATED by scripts/gen_prelude_solidified.py - DO NOT EDIT BY HAND.
//
// The shared Berry prelude (core/script/Prelude.h), compiled at build time and
// emitted as const data: every proto, constant and string below lands in flash
// .rodata instead of being parsed and built on the heap at each boot.
//
// Host bindings are referenced BY NAME (OP_GETNGBL), not by global index, so
// the bytecode binds to whatever ScriptBindings.cpp registered at runtime.
//
// The be_const_str_* symbols come from lib/berry/generate, which this script
// regenerates with coc over both lib/berry/src and this header. Commit the two
// together.
//
// C-only: be_constobj.h defines its macros under #ifndef __cplusplus. Included
// from PreludeSolidifiedLoad.c.

#include "be_constobj.h"

// input-sha256: 8e1c4117ab20a8f6990818514122cff428ce41f4eecf558c44a6c29584d46825


/********************************************************************
** Solidified function: main
********************************************************************/
be_local_closure(awtrix_prelude,   /* name */
  be_nested_proto(
    2,                          /* nstack */
    0,                          /* argc */
    0,                          /* varg */
    0,                          /* has upvals */
    NULL,                       /* no upvals */
    1,                          /* has sup protos */
    ( &(const struct bproto*[55]) {
      be_nested_proto(
        8,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 8]) {     /* constants */
        /* K0   */  be_nested_str(),
        /* K1   */  be_nested_str(find),
        /* K2   */  be_nested_str(headers),
        /* K3   */  be_nested_str(keys),
        /* K4   */  be_const_int(0),
        /* K5   */  be_nested_str(_X1F),
        /* K6   */  be_nested_str(_X3A_X20),
        /* K7   */  be_nested_str(stop_iteration),
        }),
        &be_const_str__http_headers,
        &be_const_str_solidified,
        ( &(const binstruction[39]) {  /* code */
          0x4C040000,  //  0000  LDNIL	R1
          0x1C040001,  //  0001  EQ	R1	R0	R1
          0x78060000,  //  0002  JMPF	R1	#0004
          0x80060000,  //  0003  RET	1	K0
          0x8C040101,  //  0004  GETMET	R1	R0	K1
          0x580C0002,  //  0005  LDCONST	R3	K2
          0x7C040400,  //  0006  CALL	R1	2
          0x4C080000,  //  0007  LDNIL	R2
          0x1C080202,  //  0008  EQ	R2	R1	R2
          0x780A0000,  //  0009  JMPF	R2	#000B
          0x80060000,  //  000A  RET	1	K0
          0x58080000,  //  000B  LDCONST	R2	K0
          0x600C0010,  //  000C  GETGBL	R3	G16
          0x8C100303,  //  000D  GETMET	R4	R1	K3
          0x7C100200,  //  000E  CALL	R4	1
          0x7C0C0200,  //  000F  CALL	R3	1
          0xA8020011,  //  0010  EXBLK	0	#0023
          0x5C100600,  //  0011  MOVE	R4	R3
          0x7C100000,  //  0012  CALL	R4	0
          0x6014000C,  //  0013  GETGBL	R5	G12
          0x5C180400,  //  0014  MOVE	R6	R2
          0x7C140200,  //  0015  CALL	R5	1
          0x24140B04,  //  0016  GT	R5	R5	K4
          0x78160000,  //  0017  JMPF	R5	#0019
          0x00080505,  //  0018  ADD	R2	R2	K5
          0x60140008,  //  0019  GETGBL	R5	G8
          0x5C180800,  //  001A  MOVE	R6	R4
          0x7C140200,  //  001B  CALL	R5	1
          0x00140B06,  //  001C  ADD	R5	R5	K6
          0x60180008,  //  001D  GETGBL	R6	G8
          0x941C0204,  //  001E  GETIDX	R7	R1	R4
          0x7C180200,  //  001F  CALL	R6	1
          0x00140A06,  //  0020  ADD	R5	R5	R6
          0x00080405,  //  0021  ADD	R2	R2	R5
          0x7001FFED,  //  0022  JMP		#0011
          0x580C0007,  //  0023  LDCONST	R3	K7
          0xAC0C0200,  //  0024  CATCH	R3	1	0
          0xB0080000,  //  0025  RAISE	2	R0	R0
          0x80040400,  //  0026  RET	1	R2
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(),
        /* K1   */  be_nested_str(find),
        }),
        &be_const_str__http_find,
        &be_const_str_solidified,
        ( &(const binstruction[16]) {  /* code */
          0x4C040000,  //  0000  LDNIL	R1
          0x1C040001,  //  0001  EQ	R1	R0	R1
          0x78060000,  //  0002  JMPF	R1	#0004
          0x80060000,  //  0003  RET	1	K0
          0x8C040101,  //  0004  GETMET	R1	R0	K1
          0x580C0001,  //  0005  LDCONST	R3	K1
          0x7C040400,  //  0006  CALL	R1	2
          0x4C080000,  //  0007  LDNIL	R2
          0x1C080202,  //  0008  EQ	R2	R1	R2
          0x780A0001,  //  0009  JMPF	R2	#000C
          0x58080000,  //  000A  LDCONST	R2	K0
          0x70020002,  //  000B  JMP		#000F
          0x60080008,  //  000C  GETGBL	R2	G8
          0x5C0C0200,  //  000D  MOVE	R3	R1
          0x7C080200,  //  000E  CALL	R2	1
          0x80040400,  //  000F  RET	1	R2
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 3]) {     /* constants */
        /* K0   */  be_const_int(0),
        /* K1   */  be_nested_str(find),
        /* K2   */  be_nested_str(keep),
        }),
        &be_const_str__http_keep,
        &be_const_str_solidified,
        ( &(const binstruction[16]) {  /* code */
          0x4C040000,  //  0000  LDNIL	R1
          0x1C040001,  //  0001  EQ	R1	R0	R1
          0x78060000,  //  0002  JMPF	R1	#0004
          0x80060000,  //  0003  RET	1	K0
          0x8C040101,  //  0004  GETMET	R1	R0	K1
          0x580C0002,  //  0005  LDCONST	R3	K2
          0x7C040400,  //  0006  CALL	R1	2
          0x4C080000,  //  0007  LDNIL	R2
          0x1C080202,  //  0008  EQ	R2	R1	R2
          0x780A0001,  //  0009  JMPF	R2	#000C
          0x58080000,  //  000A  LDCONST	R2	K0
          0x70020002,  //  000B  JMP		#000F
          0x60080009,  //  000C  GETGBL	R2	G9
          0x5C0C0200,  //  000D  MOVE	R3	R1
          0x7C080200,  //  000E  CALL	R2	1
          0x80040400,  //  000F  RET	1	R2
        })
      ),
      be_nested_proto(
        15,                          /* nstack */
        5,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[12]) {     /* constants */
        /* K0   */  be_nested_str(_http_next),
        /* K1   */  be_const_int(1),
        /* K2   */  be_nested_str(find),
        /* K3   */  be_nested_str(body),
        /* K4   */  be_nested_str(),
        /* K5   */  be_nested_str(_native_http_request),
        /* K6   */  be_nested_str(_http_headers),
        /* K7   */  be_nested_str(_http_find),
        /* K8   */  be_nested_str(_http_keep),
        /* K9   */  be_nested_str(_http_cbs),
        /* K10  */  be_nested_str(_native_app),
        /* K11  */  be_const_int(0),
        }),
        &be_const_str__http_send,
        &be_const_str_solidified,
        ( &(const binstruction[50]) {  /* code */
          0xB8160000,  //  0000  GETNGBL	R5	K0
          0xB81A0000,  //  0001  GETNGBL	R6	K0
          0x00180D01,  //  0002  ADD	R6	R6	K1
          0xBC1A0000,  //  0003  SETNGBL	R6	K0
          0x4C180000,  //  0004  LDNIL	R6
          0x1C180406,  //  0005  EQ	R6	R2	R6
          0x781A0006,  //  0006  JMPF	R6	#000E
          0x4C180000,  //  0007  LDNIL	R6
          0x20180806,  //  0008  NE	R6	R4	R6
          0x781A0003,  //  0009  JMPF	R6	#000E
          0x8C180902,  //  000A  GETMET	R6	R4	K2
          0x58200003,  //  000B  LDCONST	R8	K3
          0x7C180400,  //  000C  CALL	R6	2
          0x5C080C00,  //  000D  MOVE	R2	R6
          0x4C180000,  //  000E  LDNIL	R6
          0x1C180406,  //  000F  EQ	R6	R2	R6
          0x781A0000,  //  0010  JMPF	R6	#0012
          0x58080004,  //  0011  LDCONST	R2	K4
          0xB81A0A00,  //  0012  GETNGBL	R6	K5
          0x5C1C0A00,  //  0013  MOVE	R7	R5
          0x5C200000,  //  0014  MOVE	R8	R0
          0x5C240200,  //  0015  MOVE	R9	R1
          0x60280008,  //  0016  GETGBL	R10	G8
          0x5C2C0400,  //  0017  MOVE	R11	R2
          0x7C280200,  //  0018  CALL	R10	1
          0xB82E0C00,  //  0019  GETNGBL	R11	K6
          0x5C300800,  //  001A  MOVE	R12	R4
          0x7C2C0200,  //  001B  CALL	R11	1
          0xB8320E00,  //  001C  GETNGBL	R12	K7
          0x5C340800,  //  001D  MOVE	R13	R4
          0x7C300200,  //  001E  CALL	R12	1
          0xB8361000,  //  001F  GETNGBL	R13	K8
          0x5C380800,  //  0020  MOVE	R14	R4
          0x7C340200,  //  0021  CALL	R13	1
          0x7C180E00,  //  0022  CALL	R6	7
          0x781A0008,  //  0023  JMPF	R6	#002D
          0xB81A1200,  //  0024  GETNGBL	R6	K9
          0x601C0012,  //  0025  GETGBL	R7	G18
          0x7C1C0000,  //  0026  CALL	R7	0
          0xB8221400,  //  0027  GETNGBL	R8	K10
          0x7C200000,  //  0028  CALL	R8	0
          0x40200E08,  //  0029  CONNECT	R8	R7	R8
          0x40200E03,  //  002A  CONNECT	R8	R7	R3
          0x98180A07,  //  002B  SETIDX	R6	R5	R7
          0x70020003,  //  002C  JMP		#0031
          0x5C180600,  //  002D  MOVE	R6	R3
          0x4C1C0000,  //  002E  LDNIL	R7
          0x5820000B,  //  002F  LDCONST	R8	K11
          0x7C180400,  //  0030  CALL	R6	2
          0x80000000,  //  0031  RET	0
        })
      ),
      be_nested_proto(
        9,                          /* nstack */
        3,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_http_send),
        /* K1   */  be_nested_str(GET),
        }),
        &be_const_str__http_get,
        &be_const_str_solidified,
        ( &(const binstruction[ 8]) {  /* code */
          0xB80E0000,  //  0000  GETNGBL	R3	K0
          0x58100001,  //  0001  LDCONST	R4	K1
          0x5C140000,  //  0002  MOVE	R5	R0
          0x4C180000,  //  0003  LDNIL	R6
          0x5C1C0200,  //  0004  MOVE	R7	R1
          0x5C200400,  //  0005  MOVE	R8	R2
          0x7C0C0A00,  //  0006  CALL	R3	5
          0x80000000,  //  0007  RET	0
        })
      ),
      be_nested_proto(
        9,                          /* nstack */
        3,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_http_send),
        /* K1   */  be_nested_str(DELETE),
        }),
        &be_const_str__http_delete,
        &be_const_str_solidified,
        ( &(const binstruction[ 8]) {  /* code */
          0xB80E0000,  //  0000  GETNGBL	R3	K0
          0x58100001,  //  0001  LDCONST	R4	K1
          0x5C140000,  //  0002  MOVE	R5	R0
          0x4C180000,  //  0003  LDNIL	R6
          0x5C1C0200,  //  0004  MOVE	R7	R1
          0x5C200400,  //  0005  MOVE	R8	R2
          0x7C0C0A00,  //  0006  CALL	R3	5
          0x80000000,  //  0007  RET	0
        })
      ),
      be_nested_proto(
        10,                          /* nstack */
        4,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_http_send),
        /* K1   */  be_nested_str(POST),
        }),
        &be_const_str__http_post,
        &be_const_str_solidified,
        ( &(const binstruction[ 8]) {  /* code */
          0xB8120000,  //  0000  GETNGBL	R4	K0
          0x58140001,  //  0001  LDCONST	R5	K1
          0x5C180000,  //  0002  MOVE	R6	R0
          0x5C1C0200,  //  0003  MOVE	R7	R1
          0x5C200400,  //  0004  MOVE	R8	R2
          0x5C240600,  //  0005  MOVE	R9	R3
          0x7C100A00,  //  0006  CALL	R4	5
          0x80000000,  //  0007  RET	0
        })
      ),
      be_nested_proto(
        10,                          /* nstack */
        4,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_http_send),
        /* K1   */  be_nested_str(PUT),
        }),
        &be_const_str__http_put,
        &be_const_str_solidified,
        ( &(const binstruction[ 8]) {  /* code */
          0xB8120000,  //  0000  GETNGBL	R4	K0
          0x58140001,  //  0001  LDCONST	R5	K1
          0x5C180000,  //  0002  MOVE	R6	R0
          0x5C1C0200,  //  0003  MOVE	R7	R1
          0x5C200400,  //  0004  MOVE	R8	R2
          0x5C240600,  //  0005  MOVE	R9	R3
          0x7C100A00,  //  0006  CALL	R4	5
          0x80000000,  //  0007  RET	0
        })
      ),
      be_nested_proto(
        10,                          /* nstack */
        4,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_http_send),
        /* K1   */  be_nested_str(PATCH),
        }),
        &be_const_str__http_patch,
        &be_const_str_solidified,
        ( &(const binstruction[ 8]) {  /* code */
          0xB8120000,  //  0000  GETNGBL	R4	K0
          0x58140001,  //  0001  LDCONST	R5	K1
          0x5C180000,  //  0002  MOVE	R6	R0
          0x5C1C0200,  //  0003  MOVE	R7	R1
          0x5C200400,  //  0004  MOVE	R8	R2
          0x5C240600,  //  0005  MOVE	R9	R3
          0x7C100A00,  //  0006  CALL	R4	5
          0x80000000,  //  0007  RET	0
        })
      ),
      be_nested_proto(
        10,                          /* nstack */
        4,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_http_send),
        }),
        &be_const_str__http_request,
        &be_const_str_solidified,
        ( &(const binstruction[ 8]) {  /* code */
          0xB8120000,  //  0000  GETNGBL	R4	K0
          0x5C140000,  //  0001  MOVE	R5	R0
          0x5C180200,  //  0002  MOVE	R6	R1
          0x4C1C0000,  //  0003  LDNIL	R7
          0x5C200400,  //  0004  MOVE	R8	R2
          0x5C240600,  //  0005  MOVE	R9	R3
          0x7C100A00,  //  0006  CALL	R4	5
          0x80000000,  //  0007  RET	0
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        3,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 4]) {     /* constants */
        /* K0   */  be_nested_str(_http_cbs),
        /* K1   */  be_nested_str(contains),
        /* K2   */  be_nested_str(remove),
        /* K3   */  be_const_int(1),
        }),
        &be_const_str__dispatch_http,
        &be_const_str_solidified,
        ( &(const binstruction[16]) {  /* code */
          0xB80E0000,  //  0000  GETNGBL	R3	K0
          0x8C0C0701,  //  0001  GETMET	R3	R3	K1
          0x5C140000,  //  0002  MOVE	R5	R0
          0x7C0C0400,  //  0003  CALL	R3	2
          0x780E0009,  //  0004  JMPF	R3	#000F
          0xB80E0000,  //  0005  GETNGBL	R3	K0
          0x940C0600,  //  0006  GETIDX	R3	R3	R0
          0xB8120000,  //  0007  GETNGBL	R4	K0
          0x8C100902,  //  0008  GETMET	R4	R4	K2
          0x5C180000,  //  0009  MOVE	R6	R0
          0x7C100400,  //  000A  CALL	R4	2
          0x94100703,  //  000B  GETIDX	R4	R3	K3
          0x5C140200,  //  000C  MOVE	R5	R1
          0x5C180400,  //  000D  MOVE	R6	R2
          0x7C100400,  //  000E  CALL	R4	2
          0x80000000,  //  000F  RET	0
        })
      ),
      be_nested_proto(
        8,                          /* nstack */
        3,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_dispatch_http),
        }),
        &be_const_str__dispatch_http_str,
        &be_const_str_solidified,
        ( &(const binstruction[10]) {  /* code */
          0xB80E0000,  //  0000  GETNGBL	R3	K0
          0x60100009,  //  0001  GETGBL	R4	G9
          0x5C140000,  //  0002  MOVE	R5	R0
          0x7C100200,  //  0003  CALL	R4	1
          0x5C140400,  //  0004  MOVE	R5	R2
          0x60180009,  //  0005  GETGBL	R6	G9
          0x5C1C0200,  //  0006  MOVE	R7	R1
          0x7C180200,  //  0007  CALL	R6	1
          0x7C0C0600,  //  0008  CALL	R3	3
          0x80000000,  //  0009  RET	0
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_dispatch_http),
        }),
        &be_const_str__dispatch_http_fail,
        &be_const_str_solidified,
        ( &(const binstruction[10]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x600C0009,  //  0001  GETGBL	R3	G9
          0x5C100000,  //  0002  MOVE	R4	R0
          0x7C0C0200,  //  0003  CALL	R3	1
          0x4C100000,  //  0004  LDNIL	R4
          0x60140009,  //  0005  GETGBL	R5	G9
          0x5C180200,  //  0006  MOVE	R6	R1
          0x7C140200,  //  0007  CALL	R5	1
          0x7C080600,  //  0008  CALL	R2	3
          0x80000000,  //  0009  RET	0
        })
      ),
      be_nested_proto(
        6,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_mqtt_publish),
        }),
        &be_const_str__mqtt_publish,
        &be_const_str_solidified,
        ( &(const binstruction[ 7]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x5C0C0000,  //  0001  MOVE	R3	R0
          0x60100008,  //  0002  GETGBL	R4	G8
          0x5C140200,  //  0003  MOVE	R5	R1
          0x7C100200,  //  0004  CALL	R4	1
          0x7C080400,  //  0005  CALL	R2	2
          0x80000000,  //  0006  RET	0
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 4]) {     /* constants */
        /* K0   */  be_nested_str(_native_app),
        /* K1   */  be_nested_str(_mqtt_cbs),
        /* K2   */  be_nested_str(contains),
        /* K3   */  be_nested_str(_native_mqtt_subscribe),
        }),
        &be_const_str__mqtt_subscribe,
        &be_const_str_solidified,
        ( &(const binstruction[29]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x7C080000,  //  0001  CALL	R2	0
          0xB80E0200,  //  0002  GETNGBL	R3	K1
          0x8C0C0702,  //  0003  GETMET	R3	R3	K2
          0x5C140400,  //  0004  MOVE	R5	R2
          0x7C0C0400,  //  0005  CALL	R3	2
          0x740E0003,  //  0006  JMPT	R3	#000B
          0xB80E0200,  //  0007  GETNGBL	R3	K1
          0x60100013,  //  0008  GETGBL	R4	G19
          0x7C100000,  //  0009  CALL	R4	0
          0x980C0404,  //  000A  SETIDX	R3	R2	R4
          0xB80E0200,  //  000B  GETNGBL	R3	K1
          0x940C0602,  //  000C  GETIDX	R3	R3	R2
          0x8C100702,  //  000D  GETMET	R4	R3	K2
          0x5C180000,  //  000E  MOVE	R6	R0
          0x7C100400,  //  000F  CALL	R4	2
          0x74120006,  //  0010  JMPT	R4	#0018
          0x6010000C,  //  0011  GETGBL	R4	G12
          0x5C140600,  //  0012  MOVE	R5	R3
          0x7C100200,  //  0013  CALL	R4	1
          0x54160007,  //  0014  LDINT	R5	8
          0x28100805,  //  0015  GE	R4	R4	R5
          0x78120000,  //  0016  JMPF	R4	#0018
          0x80000800,  //  0017  RET	0
          0x980C0001,  //  0018  SETIDX	R3	R0	R1
          0xB8120600,  //  0019  GETNGBL	R4	K3
          0x5C140000,  //  001A  MOVE	R5	R0
          0x7C100200,  //  001B  CALL	R4	1
          0x80000000,  //  001C  RET	0
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        3,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 3]) {     /* constants */
        /* K0   */  be_nested_str(_native_app),
        /* K1   */  be_nested_str(_mqtt_cbs),
        /* K2   */  be_nested_str(contains),
        }),
        &be_const_str__dispatch_mqtt,
        &be_const_str_solidified,
        ( &(const binstruction[20]) {  /* code */
          0xB80E0000,  //  0000  GETNGBL	R3	K0
          0x7C0C0000,  //  0001  CALL	R3	0
          0xB8120200,  //  0002  GETNGBL	R4	K1
          0x8C100902,  //  0003  GETMET	R4	R4	K2
          0x5C180600,  //  0004  MOVE	R6	R3
          0x7C100400,  //  0005  CALL	R4	2
          0x7812000B,  //  0006  JMPF	R4	#0013
          0xB8120200,  //  0007  GETNGBL	R4	K1
          0x94100803,  //  0008  GETIDX	R4	R4	R3
          0x8C100902,  //  0009  GETMET	R4	R4	K2
          0x5C180000,  //  000A  MOVE	R6	R0
          0x7C100400,  //  000B  CALL	R4	2
          0x78120005,  //  000C  JMPF	R4	#0013
          0xB8120200,  //  000D  GETNGBL	R4	K1
          0x94100803,  //  000E  GETIDX	R4	R4	R3
          0x94100800,  //  000F  GETIDX	R4	R4	R0
          0x5C140200,  //  0010  MOVE	R5	R1
          0x5C180400,  //  0011  MOVE	R6	R2
          0x7C100400,  //  0012  CALL	R4	2
          0x80000000,  //  0013  RET	0
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 7]) {     /* constants */
        /* K0   */  be_nested_str(int),
        /* K1   */  be_nested_str(real),
        /* K2   */  be_const_int(0),
        /* K3   */  be_const_real_hex(0x3F000000),
        /* K4   */  be_const_int(1),
        /* K5   */  be_nested_str(stop_iteration),
        /* K6   */  be_const_real_hex(0x3F800000),
        }),
        &be_const_str_round,
        &be_const_str_solidified,
        ( &(const binstruction[52]) {  /* code */
          0x60080004,  //  0000  GETGBL	R2	G4
          0x5C0C0000,  //  0001  MOVE	R3	R0
          0x7C080200,  //  0002  CALL	R2	1
          0x1C0C0500,  //  0003  EQ	R3	R2	K0
          0x780E0000,  //  0004  JMPF	R3	#0006
          0x80040000,  //  0005  RET	1	R0
          0x200C0501,  //  0006  NE	R3	R2	K1
          0x780E0001,  //  0007  JMPF	R3	#000A
          0x4C0C0000,  //  0008  LDNIL	R3
          0x80040600,  //  0009  RET	1	R3
          0x4C0C0000,  //  000A  LDNIL	R3
          0x1C0C0203,  //  000B  EQ	R3	R1	R3
          0x740E0001,  //  000C  JMPT	R3	#000F
          0x180C0302,  //  000D  LE	R3	R1	K2
          0x780E0009,  //  000E  JMPF	R3	#0019
          0x280C0102,  //  000F  GE	R3	R0	K2
          0x780E0003,  //  0010  JMPF	R3	#0015
          0x600C0009,  //  0011  GETGBL	R3	G9
          0x00100103,  //  0012  ADD	R4	R0	K3
          0x7C0C0200,  //  0013  CALL	R3	1
          0x70020002,  //  0014  JMP		#0018
          0x600C0009,  //  0015  GETGBL	R3	G9
          0x04100103,  //  0016  SUB	R4	R0	K3
          0x7C0C0200,  //  0017  CALL	R3	1
          0x80040600,  //  0018  RET	1	R3
          0x580C0004,  //  0019  LDCONST	R3	K4
          0x60100010,  //  001A  GETGBL	R4	G16
          0x40160801,  //  001B  CONNECT	R5	K4	R1
          0x7C100200,  //  001C  CALL	R4	1
          0xA8020004,  //  001D  EXBLK	0	#0023
          0x5C140800,  //  001E  MOVE	R5	R4
          0x7C140000,  //  001F  CALL	R5	0
          0x541A0009,  //  0020  LDINT	R6	10
          0x080C0606,  //  0021  MUL	R3	R3	R6
          0x7001FFFA,  //  0022  JMP		#001E
          0x58100005,  //  0023  LDCONST	R4	K5
          0xAC100200,  //  0024  CATCH	R4	1	0
          0xB0080000,  //  0025  RAISE	2	R0	R0
          0x28100102,  //  0026  GE	R4	R0	K2
          0x78120004,  //  0027  JMPF	R4	#002D
          0x60100009,  //  0028  GETGBL	R4	G9
          0x08140003,  //  0029  MUL	R5	R0	R3
          0x00140B03,  //  002A  ADD	R5	R5	K3
          0x7C100200,  //  002B  CALL	R4	1
          0x70020003,  //  002C  JMP		#0031
          0x60100009,  //  002D  GETGBL	R4	G9
          0x08140003,  //  002E  MUL	R5	R0	R3
          0x04140B03,  //  002F  SUB	R5	R5	K3
          0x7C100200,  //  0030  CALL	R4	1
          0x08140706,  //  0031  MUL	R5	R3	K6
          0x0C140805,  //  0032  DIV	R5	R4	R5
          0x80040A00,  //  0033  RET	1	R5
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        3,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        0,                          /* has constants */
        NULL,                       /* no const */
        &be_const_str_clamp,
        &be_const_str_solidified,
        ( &(const binstruction[ 7]) {  /* code */
          0x140C0001,  //  0000  LT	R3	R0	R1
          0x780E0000,  //  0001  JMPF	R3	#0003
          0x80040200,  //  0002  RET	1	R1
          0x240C0002,  //  0003  GT	R3	R0	R2
          0x780E0000,  //  0004  JMPF	R3	#0006
          0x80040400,  //  0005  RET	1	R2
          0x80040000,  //  0006  RET	1	R0
        })
      ),
      be_nested_proto(
        3,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        0,                          /* has constants */
        NULL,                       /* no const */
        &be_const_str_min,
        &be_const_str_solidified,
        ( &(const binstruction[ 6]) {  /* code */
          0x14080001,  //  0000  LT	R2	R0	R1
          0x780A0001,  //  0001  JMPF	R2	#0004
          0x5C080000,  //  0002  MOVE	R2	R0
          0x70020000,  //  0003  JMP		#0005
          0x5C080200,  //  0004  MOVE	R2	R1
          0x80040400,  //  0005  RET	1	R2
        })
      ),
      be_nested_proto(
        3,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        0,                          /* has constants */
        NULL,                       /* no const */
        &be_const_str_max,
        &be_const_str_solidified,
        ( &(const binstruction[ 6]) {  /* code */
          0x24080001,  //  0000  GT	R2	R0	R1
          0x780A0001,  //  0001  JMPF	R2	#0004
          0x5C080000,  //  0002  MOVE	R2	R0
          0x70020000,  //  0003  JMP		#0005
          0x5C080200,  //  0004  MOVE	R2	R1
          0x80040400,  //  0005  RET	1	R2
        })
      ),
      be_nested_proto(
        6,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 5]) {     /* constants */
        /* K0   */  be_nested_str(int),
        /* K1   */  be_nested_str(real),
        /* K2   */  be_nested_str(string),
        /* K3   */  be_nested_str(json),
        /* K4   */  be_nested_str(load),
        }),
        &be_const_str_num,
        &be_const_str_solidified,
        ( &(const binstruction[41]) {  /* code */
          0x60080004,  //  0000  GETGBL	R2	G4
          0x5C0C0000,  //  0001  MOVE	R3	R0
          0x7C080200,  //  0002  CALL	R2	1
          0x1C0C0500,  //  0003  EQ	R3	R2	K0
          0x740E0001,  //  0004  JMPT	R3	#0007
          0x1C0C0501,  //  0005  EQ	R3	R2	K1
          0x780E0000,  //  0006  JMPF	R3	#0008
          0x80040000,  //  0007  RET	1	R0
          0x1C0C0502,  //  0008  EQ	R3	R2	K2
          0x780E001D,  //  0009  JMPF	R3	#0028
          0xB80E0600,  //  000A  GETNGBL	R3	K3
          0x8C0C0704,  //  000B  GETMET	R3	R3	K4
          0x5C140000,  //  000C  MOVE	R5	R0
          0x7C0C0400,  //  000D  CALL	R3	2
          0x5C000600,  //  000E  MOVE	R0	R3
          0x600C0004,  //  000F  GETGBL	R3	G4
          0x5C100000,  //  0010  MOVE	R4	R0
          0x7C0C0200,  //  0011  CALL	R3	1
          0x5C080600,  //  0012  MOVE	R2	R3
          0x1C0C0500,  //  0013  EQ	R3	R2	K0
          0x740E0001,  //  0014  JMPT	R3	#0017
          0x1C0C0501,  //  0015  EQ	R3	R2	K1
          0x780E0000,  //  0016  JMPF	R3	#0018
          0x80040000,  //  0017  RET	1	R0
          0x1C0C0502,  //  0018  EQ	R3	R2	K2
          0x780E000D,  //  0019  JMPF	R3	#0028
          0xB80E0600,  //  001A  GETNGBL	R3	K3
          0x8C0C0704,  //  001B  GETMET	R3	R3	K4
          0x5C140000,  //  001C  MOVE	R5	R0
          0x7C0C0400,  //  001D  CALL	R3	2
          0x5C000600,  //  001E  MOVE	R0	R3
          0x600C0004,  //  001F  GETGBL	R3	G4
          0x5C100000,  //  0020  MOVE	R4	R0
          0x7C0C0200,  //  0021  CALL	R3	1
          0x5C080600,  //  0022  MOVE	R2	R3
          0x1C0C0500,  //  0023  EQ	R3	R2	K0
          0x740E0001,  //  0024  JMPT	R3	#0027
          0x1C0C0501,  //  0025  EQ	R3	R2	K1
          0x780E0000,  //  0026  JMPF	R3	#0028
          0x80040000,  //  0027  RET	1	R0
          0x80040200,  //  0028  RET	1	R1
        })
      ),
      be_nested_proto(
        5,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 3]) {     /* constants */
        /* K0   */  be_nested_str(_native_notify),
        /* K1   */  be_nested_str(json),
        /* K2   */  be_nested_str(dump),
        }),
        &be_const_str_notify,
        &be_const_str_solidified,
        ( &(const binstruction[ 7]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0xB80A0200,  //  0001  GETNGBL	R2	K1
          0x8C080502,  //  0002  GETMET	R2	R2	K2
          0x5C100000,  //  0003  MOVE	R4	R0
          0x7C080400,  //  0004  CALL	R2	2
          0x7C040200,  //  0005  CALL	R1	1
          0x80040200,  //  0006  RET	1	R1
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_settings_get),
        }),
        &be_const_str__settings_get,
        &be_const_str_solidified,
        ( &(const binstruction[ 6]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x60080008,  //  0001  GETGBL	R2	G8
          0x5C0C0000,  //  0002  MOVE	R3	R0
          0x7C080200,  //  0003  CALL	R2	1
          0x7C040200,  //  0004  CALL	R1	1
          0x80040200,  //  0005  RET	1	R1
        })
      ),
      be_nested_proto(
        5,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_settings_set),
        }),
        &be_const_str__settings_set,
        &be_const_str_solidified,
        ( &(const binstruction[ 7]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x600C0008,  //  0001  GETGBL	R3	G8
          0x5C100000,  //  0002  MOVE	R4	R0
          0x7C0C0200,  //  0003  CALL	R3	1
          0x5C100200,  //  0004  MOVE	R4	R1
          0x7C080400,  //  0005  CALL	R2	2
          0x80040400,  //  0006  RET	1	R2
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_apply_case),
        }),
        &be_const_str__settings_apply_case,
        &be_const_str_solidified,
        ( &(const binstruction[ 6]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x60080008,  //  0001  GETGBL	R2	G8
          0x5C0C0000,  //  0002  MOVE	R3	R0
          0x7C080200,  //  0003  CALL	R2	1
          0x7C040200,  //  0004  CALL	R1	1
          0x80040200,  //  0005  RET	1	R1
        })
      ),
      be_nested_proto(
        5,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_native_sound),
        /* K1   */  be_const_int(0),
        }),
        &be_const_str__sound_play,
        &be_const_str_solidified,
        ( &(const binstruction[ 7]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x58080001,  //  0001  LDCONST	R2	K1
          0x600C0008,  //  0002  GETGBL	R3	G8
          0x5C100000,  //  0003  MOVE	R4	R0
          0x7C0C0200,  //  0004  CALL	R3	1
          0x7C040400,  //  0005  CALL	R1	2
          0x80040200,  //  0006  RET	1	R1
        })
      ),
      be_nested_proto(
        5,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_native_sound),
        /* K1   */  be_const_int(1),
        }),
        &be_const_str__sound_rtttl,
        &be_const_str_solidified,
        ( &(const binstruction[ 7]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x58080001,  //  0001  LDCONST	R2	K1
          0x600C0008,  //  0002  GETGBL	R3	G8
          0x5C100000,  //  0003  MOVE	R4	R0
          0x7C0C0200,  //  0004  CALL	R3	1
          0x7C040400,  //  0005  CALL	R1	2
          0x80040200,  //  0006  RET	1	R1
        })
      ),
      be_nested_proto(
        3,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 3]) {     /* constants */
        /* K0   */  be_nested_str(_native_sound),
        /* K1   */  be_const_int(2),
        /* K2   */  be_nested_str(),
        }),
        &be_const_str__sound_stop,
        &be_const_str_solidified,
        ( &(const binstruction[ 5]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x58040001,  //  0001  LDCONST	R1	K1
          0x58080002,  //  0002  LDCONST	R2	K2
          0x7C000400,  //  0003  CALL	R0	2
          0x80040000,  //  0004  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_sound_playing),
        }),
        &be_const_str__sound_playing,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_temperature),
        }),
        &be_const_str__sensor_temperature,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_humidity),
        }),
        &be_const_str__sensor_humidity,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_pressure),
        }),
        &be_const_str__sensor_pressure,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_light),
        }),
        &be_const_str__sensor_light,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_battery),
        }),
        &be_const_str__sensor_battery,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_battery_volts),
        }),
        &be_const_str__sensor_battery_volts,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_rotation_next),
        }),
        &be_const_str__rotation_next,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80000000,  //  0002  RET	0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_rotation_prev),
        }),
        &be_const_str__rotation_previous,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80000000,  //  0002  RET	0
        })
      ),
      be_nested_proto(
        2,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_rotation_hold),
        }),
        &be_const_str__rotation_pause,
        &be_const_str_solidified,
        ( &(const binstruction[ 4]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x50040200,  //  0001  LDBOOL	R1	1	0
          0x7C000200,  //  0002  CALL	R0	1
          0x80000000,  //  0003  RET	0
        })
      ),
      be_nested_proto(
        2,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_rotation_hold),
        }),
        &be_const_str__rotation_resume,
        &be_const_str_solidified,
        ( &(const binstruction[ 4]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x50040000,  //  0001  LDBOOL	R1	0	0
          0x7C000200,  //  0002  CALL	R0	1
          0x80000000,  //  0003  RET	0
        })
      ),
      be_nested_proto(
        1,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_rotation_show),
        }),
        &be_const_str__rotation_show,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0x80040000,  //  0002  RET	1	R0
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        0,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 3]) {     /* constants */
        /* K0   */  be_nested_str(_native_app),
        /* K1   */  be_nested_str(_stores),
        /* K2   */  be_nested_str(contains),
        }),
        &be_const_str__store_map,
        &be_const_str_solidified,
        ( &(const binstruction[14]) {  /* code */
          0xB8020000,  //  0000  GETNGBL	R0	K0
          0x7C000000,  //  0001  CALL	R0	0
          0xB8060200,  //  0002  GETNGBL	R1	K1
          0x8C040302,  //  0003  GETMET	R1	R1	K2
          0x5C0C0000,  //  0004  MOVE	R3	R0
          0x7C040400,  //  0005  CALL	R1	2
          0x74060003,  //  0006  JMPT	R1	#000B
          0xB8060200,  //  0007  GETNGBL	R1	K1
          0x60080013,  //  0008  GETGBL	R2	G19
          0x7C080000,  //  0009  CALL	R2	0
          0x98040002,  //  000A  SETIDX	R1	R0	R2
          0xB8060200,  //  000B  GETNGBL	R1	K1
          0x94040200,  //  000C  GETIDX	R1	R1	R0
          0x80040200,  //  000D  RET	1	R1
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 4]) {     /* constants */
        /* K0   */  be_nested_str(_store_map),
        /* K1   */  be_nested_str(_native_store_flush),
        /* K2   */  be_nested_str(json),
        /* K3   */  be_nested_str(dump),
        }),
        &be_const_str__store_set,
        &be_const_str_solidified,
        ( &(const binstruction[10]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x7C080000,  //  0001  CALL	R2	0
          0x98080001,  //  0002  SETIDX	R2	R0	R1
          0xB80E0200,  //  0003  GETNGBL	R3	K1
          0xB8120400,  //  0004  GETNGBL	R4	K2
          0x8C100903,  //  0005  GETMET	R4	R4	K3
          0x5C180400,  //  0006  MOVE	R6	R2
          0x7C100400,  //  0007  CALL	R4	2
          0x7C0C0200,  //  0008  CALL	R3	1
          0x80000000,  //  0009  RET	0
        })
      ),
      be_nested_proto(
        6,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_store_map),
        /* K1   */  be_nested_str(contains),
        }),
        &be_const_str__store_get,
        &be_const_str_solidified,
        ( &(const binstruction[ 9]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x7C080000,  //  0001  CALL	R2	0
          0x8C0C0501,  //  0002  GETMET	R3	R2	K1
          0x5C140000,  //  0003  MOVE	R5	R0
          0x7C0C0400,  //  0004  CALL	R3	2
          0x780E0001,  //  0005  JMPF	R3	#0008
          0x940C0400,  //  0006  GETIDX	R3	R2	R0
          0x80040600,  //  0007  RET	1	R3
          0x80040200,  //  0008  RET	1	R1
        })
      ),
      be_nested_proto(
        5,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 4]) {     /* constants */
        /* K0   */  be_nested_str(json),
        /* K1   */  be_nested_str(load),
        /* K2   */  be_nested_str(_stores),
        /* K3   */  be_nested_str(_native_app),
        }),
        &be_const_str__store_load,
        &be_const_str_solidified,
        ( &(const binstruction[14]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x8C040301,  //  0001  GETMET	R1	R1	K1
          0x5C0C0000,  //  0002  MOVE	R3	R0
          0x7C040400,  //  0003  CALL	R1	2
          0x6008000F,  //  0004  GETGBL	R2	G15
          0x5C0C0200,  //  0005  MOVE	R3	R1
          0x60100013,  //  0006  GETGBL	R4	G19
          0x7C080400,  //  0007  CALL	R2	2
          0x780A0003,  //  0008  JMPF	R2	#000D
          0xB80A0600,  //  0009  GETNGBL	R2	K3
          0x7C080000,  //  000A  CALL	R2	0
          0xB80E0400,  //  000B  GETNGBL	R3	K2
          0x980C0401,  //  000C  SETIDX	R3	R2	R1
          0x80000000,  //  000D  RET	0
        })
      ),
      be_nested_proto(
        5,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_shared_set),
        }),
        &be_const_str__shared_set,
        &be_const_str_solidified,
        ( &(const binstruction[ 5]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x5C0C0000,  //  0001  MOVE	R3	R0
          0x5C100200,  //  0002  MOVE	R4	R1
          0x7C080400,  //  0003  CALL	R2	2
          0x80040400,  //  0004  RET	1	R2
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_shared_get),
        }),
        &be_const_str__shared_get,
        &be_const_str_solidified,
        ( &(const binstruction[ 8]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x5C0C0000,  //  0001  MOVE	R3	R0
          0x7C080200,  //  0002  CALL	R2	1
          0x4C0C0000,  //  0003  LDNIL	R3
          0x1C0C0403,  //  0004  EQ	R3	R2	R3
          0x780E0000,  //  0005  JMPF	R3	#0007
          0x80040200,  //  0006  RET	1	R1
          0x80040400,  //  0007  RET	1	R2
        })
      ),
      be_nested_proto(
        3,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_shared_age),
        }),
        &be_const_str__shared_age,
        &be_const_str_solidified,
        ( &(const binstruction[ 4]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x5C080000,  //  0001  MOVE	R2	R0
          0x7C040200,  //  0002  CALL	R1	1
          0x80040200,  //  0003  RET	1	R1
        })
      ),
      be_nested_proto(
        3,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_native_shared_keys),
        }),
        &be_const_str__shared_keys,
        &be_const_str_solidified,
        ( &(const binstruction[ 4]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x5C080000,  //  0001  MOVE	R2	R0
          0x7C040200,  //  0002  CALL	R1	1
          0x80040200,  //  0003  RET	1	R1
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 3]) {     /* constants */
        /* K0   */  be_nested_str(_native_re_search),
        /* K1   */  be_const_int(0),
        /* K2   */  be_nested_str(remove),
        }),
        &be_const_str__re_search,
        &be_const_str_solidified,
        ( &(const binstruction[15]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x5C0C0000,  //  0001  MOVE	R3	R0
          0x5C100200,  //  0002  MOVE	R4	R1
          0x58140001,  //  0003  LDCONST	R5	K1
          0x58180001,  //  0004  LDCONST	R6	K1
          0x7C080800,  //  0005  CALL	R2	4
          0x4C0C0000,  //  0006  LDNIL	R3
          0x1C0C0403,  //  0007  EQ	R3	R2	R3
          0x780E0001,  //  0008  JMPF	R3	#000B
          0x4C0C0000,  //  0009  LDNIL	R3
          0x80040600,  //  000A  RET	1	R3
          0x8C0C0502,  //  000B  GETMET	R3	R2	K2
          0x58140001,  //  000C  LDCONST	R5	K1
          0x7C0C0400,  //  000D  CALL	R3	2
          0x80040400,  //  000E  RET	1	R2
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 4]) {     /* constants */
        /* K0   */  be_nested_str(_native_re_search),
        /* K1   */  be_const_int(0),
        /* K2   */  be_const_int(1),
        /* K3   */  be_nested_str(remove),
        }),
        &be_const_str__re_match,
        &be_const_str_solidified,
        ( &(const binstruction[15]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x5C0C0000,  //  0001  MOVE	R3	R0
          0x5C100200,  //  0002  MOVE	R4	R1
          0x58140001,  //  0003  LDCONST	R5	K1
          0x58180002,  //  0004  LDCONST	R6	K2
          0x7C080800,  //  0005  CALL	R2	4
          0x4C0C0000,  //  0006  LDNIL	R3
          0x1C0C0403,  //  0007  EQ	R3	R2	R3
          0x780E0001,  //  0008  JMPF	R3	#000B
          0x4C0C0000,  //  0009  LDNIL	R3
          0x80040600,  //  000A  RET	1	R3
          0x8C0C0503,  //  000B  GETMET	R3	R2	K3
          0x58140001,  //  000C  LDCONST	R5	K1
          0x7C0C0400,  //  000D  CALL	R3	2
          0x80040400,  //  000E  RET	1	R2
        })
      ),
      be_nested_proto(
        9,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 4]) {     /* constants */
        /* K0   */  be_const_int(0),
        /* K1   */  be_nested_str(_native_re_search),
        /* K2   */  be_nested_str(push),
        /* K3   */  be_const_int(1),
        }),
        &be_const_str__re_matchall,
        &be_const_str_solidified,
        ( &(const binstruction[31]) {  /* code */
          0x60080012,  //  0000  GETGBL	R2	G18
          0x7C080000,  //  0001  CALL	R2	0
          0x580C0000,  //  0002  LDCONST	R3	K0
          0x6010000C,  //  0003  GETGBL	R4	G12
          0x5C140200,  //  0004  MOVE	R5	R1
          0x7C100200,  //  0005  CALL	R4	1
          0x18100604,  //  0006  LE	R4	R3	R4
          0x78120015,  //  0007  JMPF	R4	#001E
          0xB8120200,  //  0008  GETNGBL	R4	K1
          0x5C140000,  //  0009  MOVE	R5	R0
          0x5C180200,  //  000A  MOVE	R6	R1
          0x5C1C0600,  //  000B  MOVE	R7	R3
          0x58200000,  //  000C  LDCONST	R8	K0
          0x7C100800,  //  000D  CALL	R4	4
          0x4C140000,  //  000E  LDNIL	R5
          0x1C140805,  //  000F  EQ	R5	R4	R5
          0x78160000,  //  0010  JMPF	R5	#0012
          0x7002000B,  //  0011  JMP		#001E
          0x8C140502,  //  0012  GETMET	R5	R2	K2
          0x941C0903,  //  0013  GETIDX	R7	R4	K3
          0x7C140400,  //  0014  CALL	R5	2
          0x94140900,  //  0015  GETIDX	R5	R4	K0
          0x24140A03,  //  0016  GT	R5	R5	R3
          0x78160003,  //  0017  JMPF	R5	#001C
          0x94140900,  //  0018  GETIDX	R5	R4	K0
          0x00140B00,  //  0019  ADD	R5	R5	K0
          0x5C0C0A00,  //  001A  MOVE	R3	R5
          0x70020000,  //  001B  JMP		#001D
          0x000C0703,  //  001C  ADD	R3	R3	K3
          0x7001FFE4,  //  001D  JMP		#0003
          0x80040400,  //  001E  RET	1	R2
        })
      ),
      be_nested_proto(
        3,                          /* nstack */
        2,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 1]) {     /* constants */
        /* K0   */  be_nested_str(_apps),
        }),
        &be_const_str__app_anchor,
        &be_const_str_solidified,
        ( &(const binstruction[ 3]) {  /* code */
          0xB80A0000,  //  0000  GETNGBL	R2	K0
          0x98080001,  //  0001  SETIDX	R2	R0	R1
          0x80000000,  //  0002  RET	0
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 2]) {     /* constants */
        /* K0   */  be_nested_str(_apps),
        /* K1   */  be_nested_str(contains),
        }),
        &be_const_str__app_instance,
        &be_const_str_solidified,
        ( &(const binstruction[10]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x8C040301,  //  0001  GETMET	R1	R1	K1
          0x5C0C0000,  //  0002  MOVE	R3	R0
          0x7C040400,  //  0003  CALL	R1	2
          0x78060002,  //  0004  JMPF	R1	#0008
          0xB8060000,  //  0005  GETNGBL	R1	K0
          0x94040200,  //  0006  GETIDX	R1	R1	R0
          0x80040200,  //  0007  RET	1	R1
          0x4C040000,  //  0008  LDNIL	R1
          0x80040200,  //  0009  RET	1	R1
        })
      ),
      be_nested_proto(
        4,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 3]) {     /* constants */
        /* K0   */  be_nested_str(_apps),
        /* K1   */  be_nested_str(contains),
        /* K2   */  be_nested_str(remove),
        }),
        &be_const_str__app_drop,
        &be_const_str_solidified,
        ( &(const binstruction[10]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x8C040301,  //  0001  GETMET	R1	R1	K1
          0x5C0C0000,  //  0002  MOVE	R3	R0
          0x7C040400,  //  0003  CALL	R1	2
          0x78060003,  //  0004  JMPF	R1	#0009
          0xB8060000,  //  0005  GETNGBL	R1	K0
          0x8C040302,  //  0006  GETMET	R1	R1	K2
          0x5C0C0000,  //  0007  MOVE	R3	R0
          0x7C040400,  //  0008  CALL	R1	2
          0x80000000,  //  0009  RET	0
        })
      ),
      be_nested_proto(
        7,                          /* nstack */
        1,                          /* argc */
        0,                          /* varg */
        0,                          /* has upvals */
        NULL,                       /* no upvals */
        0,                          /* has sup protos */
        NULL,                       /* no sub protos */
        1,                          /* has constants */
        ( &(const bvalue[ 9]) {     /* constants */
        /* K0   */  be_nested_str(_stores),
        /* K1   */  be_nested_str(contains),
        /* K2   */  be_nested_str(remove),
        /* K3   */  be_nested_str(_mqtt_cbs),
        /* K4   */  be_nested_str(_http_cbs),
        /* K5   */  be_nested_str(keys),
        /* K6   */  be_const_int(0),
        /* K7   */  be_nested_str(push),
        /* K8   */  be_nested_str(stop_iteration),
        }),
        &be_const_str__app_forget,
        &be_const_str_solidified,
        ( &(const binstruction[55]) {  /* code */
          0xB8060000,  //  0000  GETNGBL	R1	K0
          0x8C040301,  //  0001  GETMET	R1	R1	K1
          0x5C0C0000,  //  0002  MOVE	R3	R0
          0x7C040400,  //  0003  CALL	R1	2
          0x78060003,  //  0004  JMPF	R1	#0009
          0xB8060000,  //  0005  GETNGBL	R1	K0
          0x8C040302,  //  0006  GETMET	R1	R1	K2
          0x5C0C0000,  //  0007  MOVE	R3	R0
          0x7C040400,  //  0008  CALL	R1	2
          0xB8060600,  //  0009  GETNGBL	R1	K3
          0x8C040301,  //  000A  GETMET	R1	R1	K1
          0x5C0C0000,  //  000B  MOVE	R3	R0
          0x7C040400,  //  000C  CALL	R1	2
          0x78060003,  //  000D  JMPF	R1	#0012
          0xB8060600,  //  000E  GETNGBL	R1	K3
          0x8C040302,  //  000F  GETMET	R1	R1	K2
          0x5C0C0000,  //  0010  MOVE	R3	R0
          0x7C040400,  //  0011  CALL	R1	2
          0x60040012,  //  0012  GETGBL	R1	G18
          0x7C040000,  //  0013  CALL	R1	0
          0x60080010,  //  0014  GETGBL	R2	G16
          0xB80E0800,  //  0015  GETNGBL	R3	K4
          0x8C0C0705,  //  0016  GETMET	R3	R3	K5
          0x7C0C0200,  //  0017  CALL	R3	1
          0x7C080200,  //  0018  CALL	R2	1
          0xA802000A,  //  0019  EXBLK	0	#0025
          0x5C0C0400,  //  001A  MOVE	R3	R2
          0x7C0C0000,  //  001B  CALL	R3	0
          0xB8120800,  //  001C  GETNGBL	R4	K4
          0x94100803,  //  001D  GETIDX	R4	R4	R3
          0x94100906,  //  001E  GETIDX	R4	R4	K6
          0x1C100800,  //  001F  EQ	R4	R4	R0
          0x78120002,  //  0020  JMPF	R4	#0024
          0x8C100307,  //  0021  GETMET	R4	R1	K7
          0x5C180600,  //  0022  MOVE	R6	R3
          0x7C100400,  //  0023  CALL	R4	2
          0x7001FFF4,  //  0024  JMP		#001A
          0x58080008,  //  0025  LDCONST	R2	K8
          0xAC080200,  //  0026  CATCH	R2	1	0
          0xB0080000,  //  0027  RAISE	2	R0	R0
          0x60080010,  //  0028  GETGBL	R2	G16
          0x5C0C0200,  //  0029  MOVE	R3	R1
          0x7C080200,  //  002A  CALL	R2	1
          0xA8020006,  //  002B  EXBLK	0	#0033
          0x5C0C0400,  //  002C  MOVE	R3	R2
          0x7C0C0000,  //  002D  CALL	R3	0
          0xB8120800,  //  002E  GETNGBL	R4	K4
          0x8C100902,  //  002F  GETMET	R4	R4	K2
          0x5C180600,  //  0030  MOVE	R6	R3
          0x7C100400,  //  0031  CALL	R4	2
          0x7001FFF8,  //  0032  JMP		#002C
          0x58080008,  //  0033  LDCONST	R2	K8
          0xAC080200,  //  0034  CATCH	R2	1	0
          0xB0080000,  //  0035  RAISE	2	R0	R0
          0x80000000,  //  0036  RET	0
        })
      ),
    }),
    1,                          /* has constants */
    ( &(const bvalue[146]) {     /* constants */
    /* K0   */  be_nested_str(json),
    /* K1   */  be_nested_str(http),
    /* K2   */  be_nested_str(_http_cbs),
    /* K3   */  be_nested_str(_http_next),
    /* K4   */  be_const_int(1),
    /* K5   */  be_nested_str(_http_headers),
    /* K6   */  be_nested_str(_http_find),
    /* K7   */  be_nested_str(_http_keep),
    /* K8   */  be_nested_str(_http_send),
    /* K9   */  be_nested_str(_http_get),
    /* K10  */  be_nested_str(_http_delete),
    /* K11  */  be_nested_str(_http_post),
    /* K12  */  be_nested_str(_http_put),
    /* K13  */  be_nested_str(_http_patch),
    /* K14  */  be_nested_str(_http_request),
    /* K15  */  be_nested_str(get),
    /* K16  */  be_nested_str(delete),
    /* K17  */  be_nested_str(post),
    /* K18  */  be_nested_str(put),
    /* K19  */  be_nested_str(patch),
    /* K20  */  be_nested_str(request),
    /* K21  */  be_nested_str(_dispatch_http),
    /* K22  */  be_nested_str(_dispatch_http_str),
    /* K23  */  be_nested_str(_dispatch_http_fail),
    /* K24  */  be_nested_str(mqtt),
    /* K25  */  be_nested_str(_mqtt_cbs),
    /* K26  */  be_nested_str(_mqtt_publish),
    /* K27  */  be_nested_str(_mqtt_subscribe),
    /* K28  */  be_nested_str(publish),
    /* K29  */  be_nested_str(subscribe),
    /* K30  */  be_nested_str(_dispatch_mqtt),
    /* K31  */  be_nested_str(round),
    /* K32  */  be_nested_str(clamp),
    /* K33  */  be_nested_str(min),
    /* K34  */  be_nested_str(max),
    /* K35  */  be_nested_str(num),
    /* K36  */  be_nested_str(notify),
    /* K37  */  be_nested_str(settings),
    /* K38  */  be_nested_str(_settings_get),
    /* K39  */  be_nested_str(_settings_set),
    /* K40  */  be_nested_str(_settings_apply_case),
    /* K41  */  be_nested_str(set),
    /* K42  */  be_nested_str(apply_case),
    /* K43  */  be_nested_str(sound),
    /* K44  */  be_nested_str(_sound_play),
    /* K45  */  be_nested_str(_sound_rtttl),
    /* K46  */  be_nested_str(_sound_stop),
    /* K47  */  be_nested_str(_sound_playing),
    /* K48  */  be_nested_str(play),
    /* K49  */  be_nested_str(rtttl),
    /* K50  */  be_nested_str(stop),
    /* K51  */  be_nested_str(playing),
    /* K52  */  be_nested_str(sensor),
    /* K53  */  be_nested_str(sensor),
    /* K54  */  be_nested_str(_sensor_temperature),
    /* K55  */  be_nested_str(_sensor_humidity),
    /* K56  */  be_nested_str(_sensor_pressure),
    /* K57  */  be_nested_str(_sensor_light),
    /* K58  */  be_nested_str(_sensor_battery),
    /* K59  */  be_nested_str(_sensor_battery_volts),
    /* K60  */  be_nested_str(sensor),
    /* K61  */  be_nested_str(temperature),
    /* K62  */  be_nested_str(_sensor_temperature),
    /* K63  */  be_nested_str(sensor),
    /* K64  */  be_nested_str(humidity),
    /* K65  */  be_nested_str(_sensor_humidity),
    /* K66  */  be_nested_str(sensor),
    /* K67  */  be_nested_str(pressure),
    /* K68  */  be_nested_str(_sensor_pressure),
    /* K69  */  be_nested_str(sensor),
    /* K70  */  be_nested_str(light),
    /* K71  */  be_nested_str(_sensor_light),
    /* K72  */  be_nested_str(sensor),
    /* K73  */  be_nested_str(battery),
    /* K74  */  be_nested_str(_sensor_battery),
    /* K75  */  be_nested_str(sensor),
    /* K76  */  be_nested_str(battery_volts),
    /* K77  */  be_nested_str(_sensor_battery_volts),
    /* K78  */  be_nested_str(rotation),
    /* K79  */  be_nested_str(rotation),
    /* K80  */  be_nested_str(_rotation_next),
    /* K81  */  be_nested_str(_rotation_previous),
    /* K82  */  be_nested_str(_rotation_pause),
    /* K83  */  be_nested_str(_rotation_resume),
    /* K84  */  be_nested_str(_rotation_show),
    /* K85  */  be_nested_str(rotation),
    /* K86  */  be_nested_str(next),
    /* K87  */  be_nested_str(_rotation_next),
    /* K88  */  be_nested_str(rotation),
    /* K89  */  be_nested_str(previous),
    /* K90  */  be_nested_str(_rotation_previous),
    /* K91  */  be_nested_str(rotation),
    /* K92  */  be_nested_str(pause),
    /* K93  */  be_nested_str(_rotation_pause),
    /* K94  */  be_nested_str(rotation),
    /* K95  */  be_nested_str(resume),
    /* K96  */  be_nested_str(_rotation_resume),
    /* K97  */  be_nested_str(rotation),
    /* K98  */  be_nested_str(show),
    /* K99  */  be_nested_str(_rotation_show),
    /* K100 */  be_nested_str(store),
    /* K101 */  be_nested_str(store),
    /* K102 */  be_nested_str(_stores),
    /* K103 */  be_nested_str(_store_map),
    /* K104 */  be_nested_str(_store_set),
    /* K105 */  be_nested_str(_store_get),
    /* K106 */  be_nested_str(store),
    /* K107 */  be_nested_str(_store_set),
    /* K108 */  be_nested_str(store),
    /* K109 */  be_nested_str(_store_get),
    /* K110 */  be_nested_str(_store_load),
    /* K111 */  be_nested_str(shared),
    /* K112 */  be_nested_str(shared),
    /* K113 */  be_nested_str(_shared_set),
    /* K114 */  be_nested_str(_shared_get),
    /* K115 */  be_nested_str(_shared_age),
    /* K116 */  be_nested_str(_shared_keys),
    /* K117 */  be_nested_str(shared),
    /* K118 */  be_nested_str(_shared_set),
    /* K119 */  be_nested_str(shared),
    /* K120 */  be_nested_str(_shared_get),
    /* K121 */  be_nested_str(shared),
    /* K122 */  be_nested_str(age),
    /* K123 */  be_nested_str(_shared_age),
    /* K124 */  be_nested_str(shared),
    /* K125 */  be_nested_str(keys),
    /* K126 */  be_nested_str(_shared_keys),
    /* K127 */  be_nested_str(re),
    /* K128 */  be_nested_str(re),
    /* K129 */  be_nested_str(_re_search),
    /* K130 */  be_nested_str(_re_match),
    /* K131 */  be_nested_str(_re_matchall),
    /* K132 */  be_nested_str(re),
    /* K133 */  be_nested_str(search),
    /* K134 */  be_nested_str(_re_search),
    /* K135 */  be_nested_str(re),
    /* K136 */  be_nested_str(match),
    /* K137 */  be_nested_str(_re_match),
    /* K138 */  be_nested_str(re),
    /* K139 */  be_nested_str(matchall),
    /* K140 */  be_nested_str(_re_matchall),
    /* K141 */  be_nested_str(_apps),
    /* K142 */  be_nested_str(_app_anchor),
    /* K143 */  be_nested_str(_app_instance),
    /* K144 */  be_nested_str(_app_drop),
    /* K145 */  be_nested_str(_app_forget),
    }),
    &be_const_str_main,
    &be_const_str_solidified,
    ( &(const binstruction[268]) {  /* code */
      0xA4020000,  //  0000  IMPORT	R0	K0
      0xBC020000,  //  0001  SETNGBL	R0	K0
      0x6000000B,  //  0002  GETGBL	R0	G11
      0x58040001,  //  0003  LDCONST	R1	K1
      0x7C000200,  //  0004  CALL	R0	1
      0xBC020200,  //  0005  SETNGBL	R0	K1
      0x60000013,  //  0006  GETGBL	R0	G19
      0x7C000000,  //  0007  CALL	R0	0
      0xBC020400,  //  0008  SETNGBL	R0	K2
      0x58000004,  //  0009  LDCONST	R0	K4
      0xBC020600,  //  000A  SETNGBL	R0	K3
      0x84000000,  //  000B  CLOSURE	R0	P0
      0xBC020A00,  //  000C  SETNGBL	R0	K5
      0x84000001,  //  000D  CLOSURE	R0	P1
      0xBC020C00,  //  000E  SETNGBL	R0	K6
      0x84000002,  //  000F  CLOSURE	R0	P2
      0xBC020E00,  //  0010  SETNGBL	R0	K7
      0x84000003,  //  0011  CLOSURE	R0	P3
      0xBC021000,  //  0012  SETNGBL	R0	K8
      0x84000004,  //  0013  CLOSURE	R0	P4
      0xBC021200,  //  0014  SETNGBL	R0	K9
      0x84000005,  //  0015  CLOSURE	R0	P5
      0xBC021400,  //  0016  SETNGBL	R0	K10
      0x84000006,  //  0017  CLOSURE	R0	P6
      0xBC021600,  //  0018  SETNGBL	R0	K11
      0x84000007,  //  0019  CLOSURE	R0	P7
      0xBC021800,  //  001A  SETNGBL	R0	K12
      0x84000008,  //  001B  CLOSURE	R0	P8
      0xBC021A00,  //  001C  SETNGBL	R0	K13
      0x84000009,  //  001D  CLOSURE	R0	P9
      0xBC021C00,  //  001E  SETNGBL	R0	K14
      0xB8020200,  //  001F  GETNGBL	R0	K1
      0xB8061200,  //  0020  GETNGBL	R1	K9
      0x90021E01,  //  0021  SETMBR	R0	K15	R1
      0xB8020200,  //  0022  GETNGBL	R0	K1
      0xB8061400,  //  0023  GETNGBL	R1	K10
      0x90022001,  //  0024  SETMBR	R0	K16	R1
      0xB8020200,  //  0025  GETNGBL	R0	K1
      0xB8061600,  //  0026  GETNGBL	R1	K11
      0x90022201,  //  0027  SETMBR	R0	K17	R1
      0xB8020200,  //  0028  GETNGBL	R0	K1
      0xB8061800,  //  0029  GETNGBL	R1	K12
      0x90022401,  //  002A  SETMBR	R0	K18	R1
      0xB8020200,  //  002B  GETNGBL	R0	K1
      0xB8061A00,  //  002C  GETNGBL	R1	K13
      0x90022601,  //  002D  SETMBR	R0	K19	R1
      0xB8020200,  //  002E  GETNGBL	R0	K1
      0xB8061C00,  //  002F  GETNGBL	R1	K14
      0x90022801,  //  0030  SETMBR	R0	K20	R1
      0x8400000A,  //  0031  CLOSURE	R0	P10
      0xBC022A00,  //  0032  SETNGBL	R0	K21
      0x8400000B,  //  0033  CLOSURE	R0	P11
      0xBC022C00,  //  0034  SETNGBL	R0	K22
      0x8400000C,  //  0035  CLOSURE	R0	P12
      0xBC022E00,  //  0036  SETNGBL	R0	K23
      0x6000000B,  //  0037  GETGBL	R0	G11
      0x58040018,  //  0038  LDCONST	R1	K24
      0x7C000200,  //  0039  CALL	R0	1
      0xBC023000,  //  003A  SETNGBL	R0	K24
      0x60000013,  //  003B  GETGBL	R0	G19
      0x7C000000,  //  003C  CALL	R0	0
      0xBC023200,  //  003D  SETNGBL	R0	K25
      0x8400000D,  //  003E  CLOSURE	R0	P13
      0xBC023400,  //  003F  SETNGBL	R0	K26
      0x8400000E,  //  0040  CLOSURE	R0	P14
      0xBC023600,  //  0041  SETNGBL	R0	K27
      0xB8023000,  //  0042  GETNGBL	R0	K24
      0xB8063400,  //  0043  GETNGBL	R1	K26
      0x90023801,  //  0044  SETMBR	R0	K28	R1
      0xB8023000,  //  0045  GETNGBL	R0	K24
      0xB8063600,  //  0046  GETNGBL	R1	K27
      0x90023A01,  //  0047  SETMBR	R0	K29	R1
      0x8400000F,  //  0048  CLOSURE	R0	P15
      0xBC023C00,  //  0049  SETNGBL	R0	K30
      0x84000010,  //  004A  CLOSURE	R0	P16
      0xBC023E00,  //  004B  SETNGBL	R0	K31
      0x84000011,  //  004C  CLOSURE	R0	P17
      0xBC024000,  //  004D  SETNGBL	R0	K32
      0x84000012,  //  004E  CLOSURE	R0	P18
      0xBC024200,  //  004F  SETNGBL	R0	K33
      0x84000013,  //  0050  CLOSURE	R0	P19
      0xBC024400,  //  0051  SETNGBL	R0	K34
      0x84000014,  //  0052  CLOSURE	R0	P20
      0xBC024600,  //  0053  SETNGBL	R0	K35
      0x84000015,  //  0054  CLOSURE	R0	P21
      0xBC024800,  //  0055  SETNGBL	R0	K36
      0x6000000B,  //  0056  GETGBL	R0	G11
      0x58040025,  //  0057  LDCONST	R1	K37
      0x7C000200,  //  0058  CALL	R0	1
      0xBC024A00,  //  0059  SETNGBL	R0	K37
      0x84000016,  //  005A  CLOSURE	R0	P22
      0xBC024C00,  //  005B  SETNGBL	R0	K38
      0x84000017,  //  005C  CLOSURE	R0	P23
      0xBC024E00,  //  005D  SETNGBL	R0	K39
      0x84000018,  //  005E  CLOSURE	R0	P24
      0xBC025000,  //  005F  SETNGBL	R0	K40
      0xB8024A00,  //  0060  GETNGBL	R0	K37
      0xB8064C00,  //  0061  GETNGBL	R1	K38
      0x90021E01,  //  0062  SETMBR	R0	K15	R1
      0xB8024A00,  //  0063  GETNGBL	R0	K37
      0xB8064E00,  //  0064  GETNGBL	R1	K39
      0x90025201,  //  0065  SETMBR	R0	K41	R1
      0xB8024A00,  //  0066  GETNGBL	R0	K37
      0xB8065000,  //  0067  GETNGBL	R1	K40
      0x90025401,  //  0068  SETMBR	R0	K42	R1
      0x6000000B,  //  0069  GETGBL	R0	G11
      0x5804002B,  //  006A  LDCONST	R1	K43
      0x7C000200,  //  006B  CALL	R0	1
      0xBC025600,  //  006C  SETNGBL	R0	K43
      0x84000019,  //  006D  CLOSURE	R0	P25
      0xBC025800,  //  006E  SETNGBL	R0	K44
      0x8400001A,  //  006F  CLOSURE	R0	P26
      0xBC025A00,  //  0070  SETNGBL	R0	K45
      0x8400001B,  //  0071  CLOSURE	R0	P27
      0xBC025C00,  //  0072  SETNGBL	R0	K46
      0x8400001C,  //  0073  CLOSURE	R0	P28
      0xBC025E00,  //  0074  SETNGBL	R0	K47
      0xB8025600,  //  0075  GETNGBL	R0	K43
      0xB8065800,  //  0076  GETNGBL	R1	K44
      0x90026001,  //  0077  SETMBR	R0	K48	R1
      0xB8025600,  //  0078  GETNGBL	R0	K43
      0xB8065A00,  //  0079  GETNGBL	R1	K45
      0x90026201,  //  007A  SETMBR	R0	K49	R1
      0xB8025600,  //  007B  GETNGBL	R0	K43
      0xB8065C00,  //  007C  GETNGBL	R1	K46
      0x90026401,  //  007D  SETMBR	R0	K50	R1
      0xB8025600,  //  007E  GETNGBL	R0	K43
      0xB8065E00,  //  007F  GETNGBL	R1	K47
      0x90026601,  //  0080  SETMBR	R0	K51	R1
      0x6000000B,  //  0081  GETGBL	R0	G11
      0x58040034,  //  0082  LDCONST	R1	K52
      0x7C000200,  //  0083  CALL	R0	1
      0xBC026A00,  //  0084  SETNGBL	R0	K53
      0x8400001D,  //  0085  CLOSURE	R0	P29
      0xBC026C00,  //  0086  SETNGBL	R0	K54
      0x8400001E,  //  0087  CLOSURE	R0	P30
      0xBC026E00,  //  0088  SETNGBL	R0	K55
      0x8400001F,  //  0089  CLOSURE	R0	P31
      0xBC027000,  //  008A  SETNGBL	R0	K56
      0x84000020,  //  008B  CLOSURE	R0	P32
      0xBC027200,  //  008C  SETNGBL	R0	K57
      0x84000021,  //  008D  CLOSURE	R0	P33
      0xBC027400,  //  008E  SETNGBL	R0	K58
      0x84000022,  //  008F  CLOSURE	R0	P34
      0xBC027600,  //  0090  SETNGBL	R0	K59
      0xB8027800,  //  0091  GETNGBL	R0	K60
      0xB8067C00,  //  0092  GETNGBL	R1	K62
      0x90027A01,  //  0093  SETMBR	R0	K61	R1
      0xB8027E00,  //  0094  GETNGBL	R0	K63
      0xB8068200,  //  0095  GETNGBL	R1	K65
      0x90028001,  //  0096  SETMBR	R0	K64	R1
      0xB8028400,  //  0097  GETNGBL	R0	K66
      0xB8068800,  //  0098  GETNGBL	R1	K68
      0x90028601,  //  0099  SETMBR	R0	K67	R1
      0xB8028A00,  //  009A  GETNGBL	R0	K69
      0xB8068E00,  //  009B  GETNGBL	R1	K71
      0x90028C01,  //  009C  SETMBR	R0	K70	R1
      0xB8029000,  //  009D  GETNGBL	R0	K72
      0xB8069400,  //  009E  GETNGBL	R1	K74
      0x90029201,  //  009F  SETMBR	R0	K73	R1
      0xB8029600,  //  00A0  GETNGBL	R0	K75
      0xB8069A00,  //  00A1  GETNGBL	R1	K77
      0x90029801,  //  00A2  SETMBR	R0	K76	R1
      0x6000000B,  //  00A3  GETGBL	R0	G11
      0x5804004E,  //  00A4  LDCONST	R1	K78
      0x7C000200,  //  00A5  CALL	R0	1
      0xBC029E00,  //  00A6  SETNGBL	R0	K79
      0x84000023,  //  00A7  CLOSURE	R0	P35
      0xBC02A000,  //  00A8  SETNGBL	R0	K80
      0x84000024,  //  00A9  CLOSURE	R0	P36
      0xBC02A200,  //  00AA  SETNGBL	R0	K81
      0x84000025,  //  00AB  CLOSURE	R0	P37
      0xBC02A400,  //  00AC  SETNGBL	R0	K82
      0x84000026,  //  00AD  CLOSURE	R0	P38
      0xBC02A600,  //  00AE  SETNGBL	R0	K83
      0x84000027,  //  00AF  CLOSURE	R0	P39
      0xBC02A800,  //  00B0  SETNGBL	R0	K84
      0xB802AA00,  //  00B1  GETNGBL	R0	K85
      0xB806AE00,  //  00B2  GETNGBL	R1	K87
      0x9002AC01,  //  00B3  SETMBR	R0	K86	R1
      0xB802B000,  //  00B4  GETNGBL	R0	K88
      0xB806B400,  //  00B5  GETNGBL	R1	K90
      0x9002B201,  //  00B6  SETMBR	R0	K89	R1
      0xB802B600,  //  00B7  GETNGBL	R0	K91
      0xB806BA00,  //  00B8  GETNGBL	R1	K93
      0x9002B801,  //  00B9  SETMBR	R0	K92	R1
      0xB802BC00,  //  00BA  GETNGBL	R0	K94
      0xB806C000,  //  00BB  GETNGBL	R1	K96
      0x9002BE01,  //  00BC  SETMBR	R0	K95	R1
      0xB802C200,  //  00BD  GETNGBL	R0	K97
      0xB806C600,  //  00BE  GETNGBL	R1	K99
      0x9002C401,  //  00BF  SETMBR	R0	K98	R1
      0x6000000B,  //  00C0  GETGBL	R0	G11
      0x58040064,  //  00C1  LDCONST	R1	K100
      0x7C000200,  //  00C2  CALL	R0	1
      0xBC02CA00,  //  00C3  SETNGBL	R0	K101
      0x60000013,  //  00C4  GETGBL	R0	G19
      0x7C000000,  //  00C5  CALL	R0	0
      0xBC02CC00,  //  00C6  SETNGBL	R0	K102
      0x84000028,  //  00C7  CLOSURE	R0	P40
      0xBC02CE00,  //  00C8  SETNGBL	R0	K103
      0x84000029,  //  00C9  CLOSURE	R0	P41
      0xBC02D000,  //  00CA  SETNGBL	R0	K104
      0x8400002A,  //  00CB  CLOSURE	R0	P42
      0xBC02D200,  //  00CC  SETNGBL	R0	K105
      0xB802D400,  //  00CD  GETNGBL	R0	K106
      0xB806D600,  //  00CE  GETNGBL	R1	K107
      0x90025201,  //  00CF  SETMBR	R0	K41	R1
      0xB802D800,  //  00D0  GETNGBL	R0	K108
      0xB806DA00,  //  00D1  GETNGBL	R1	K109
      0x90021E01,  //  00D2  SETMBR	R0	K15	R1
      0x8400002B,  //  00D3  CLOSURE	R0	P43
      0xBC02DC00,  //  00D4  SETNGBL	R0	K110
      0x6000000B,  //  00D5  GETGBL	R0	G11
      0x5804006F,  //  00D6  LDCONST	R1	K111
      0x7C000200,  //  00D7  CALL	R0	1
      0xBC02E000,  //  00D8  SETNGBL	R0	K112
      0x8400002C,  //  00D9  CLOSURE	R0	P44
      0xBC02E200,  //  00DA  SETNGBL	R0	K113
      0x8400002D,  //  00DB  CLOSURE	R0	P45
      0xBC02E400,  //  00DC  SETNGBL	R0	K114
      0x8400002E,  //  00DD  CLOSURE	R0	P46
      0xBC02E600,  //  00DE  SETNGBL	R0	K115
      0x8400002F,  //  00DF  CLOSURE	R0	P47
      0xBC02E800,  //  00E0  SETNGBL	R0	K116
      0xB802EA00,  //  00E1  GETNGBL	R0	K117
      0xB806EC00,  //  00E2  GETNGBL	R1	K118
      0x90025201,  //  00E3  SETMBR	R0	K41	R1
      0xB802EE00,  //  00E4  GETNGBL	R0	K119
      0xB806F000,  //  00E5  GETNGBL	R1	K120
      0x90021E01,  //  00E6  SETMBR	R0	K15	R1
      0xB802F200,  //  00E7  GETNGBL	R0	K121
      0xB806F600,  //  00E8  GETNGBL	R1	K123
      0x9002F401,  //  00E9  SETMBR	R0	K122	R1
      0xB802F800,  //  00EA  GETNGBL	R0	K124
      0xB806FC00,  //  00EB  GETNGBL	R1	K126
      0x9002FA01,  //  00EC  SETMBR	R0	K125	R1
      0x6000000B,  //  00ED  GETGBL	R0	G11
      0x5804007F,  //  00EE  LDCONST	R1	K127
      0x7C000200,  //  00EF  CALL	R0	1
      0xBC030000,  //  00F0  SETNGBL	R0	K128
      0x84000030,  //  00F1  CLOSURE	R0	P48
      0xBC030200,  //  00F2  SETNGBL	R0	K129
      0x84000031,  //  00F3  CLOSURE	R0	P49
      0xBC030400,  //  00F4  SETNGBL	R0	K130
      0x84000032,  //  00F5  CLOSURE	R0	P50
      0xBC030600,  //  00F6  SETNGBL	R0	K131
      0xB8030800,  //  00F7  GETNGBL	R0	K132
      0xB8070C00,  //  00F8  GETNGBL	R1	K134
      0x90030A01,  //  00F9  SETMBR	R0	K133	R1
      0xB8030E00,  //  00FA  GETNGBL	R0	K135
      0xB8071200,  //  00FB  GETNGBL	R1	K137
      0x90031001,  //  00FC  SETMBR	R0	K136	R1
      0xB8031400,  //  00FD  GETNGBL	R0	K138
      0xB8071800,  //  00FE  GETNGBL	R1	K140
      0x90031601,  //  00FF  SETMBR	R0	K139	R1
      0x60000013,  //  0100  GETGBL	R0	G19
      0x7C000000,  //  0101  CALL	R0	0
      0xBC031A00,  //  0102  SETNGBL	R0	K141
      0x84000033,  //  0103  CLOSURE	R0	P51
      0xBC031C00,  //  0104  SETNGBL	R0	K142
      0x84000034,  //  0105  CLOSURE	R0	P52
      0xBC031E00,  //  0106  SETNGBL	R0	K143
      0x84000035,  //  0107  CLOSURE	R0	P53
      0xBC032000,  //  0108  SETNGBL	R0	K144
      0x84000036,  //  0109  CLOSURE	R0	P54
      0xBC032200,  //  010A  SETNGBL	R0	K145
      0x80000000,  //  010B  RET	0
    })
  )
);
/*******************************************************************/


/* Binding-name anchor: every global ScriptBindings.cpp registers,
 * referenced once so coc emits the names into the const string table
 * and be_regfunc() finds them in flash instead of interning per boot. */
static const bvalue awtrix_binding_name_anchor[]
    __attribute__((unused)) = {
  be_nested_str(_native_app),
  be_nested_str(_native_apply_case),
  be_nested_str(_native_battery),
  be_nested_str(_native_battery_volts),
  be_nested_str(_native_http_request),
  be_nested_str(_native_humidity),
  be_nested_str(_native_light),
  be_nested_str(_native_mqtt_publish),
  be_nested_str(_native_mqtt_subscribe),
  be_nested_str(_native_notify),
  be_nested_str(_native_pressure),
  be_nested_str(_native_re_search),
  be_nested_str(_native_rotation_hold),
  be_nested_str(_native_rotation_next),
  be_nested_str(_native_rotation_prev),
  be_nested_str(_native_rotation_show),
  be_nested_str(_native_settings_get),
  be_nested_str(_native_settings_set),
  be_nested_str(_native_shared_age),
  be_nested_str(_native_shared_get),
  be_nested_str(_native_shared_keys),
  be_nested_str(_native_shared_set),
  be_nested_str(_native_sound),
  be_nested_str(_native_sound_playing),
  be_nested_str(_native_store_flush),
  be_nested_str(_native_temperature),
  be_nested_str(bar_chart),
  be_nested_str(circle),
  be_nested_str(circle_fill),
  be_nested_str(clear),
  be_nested_str(day),
  be_nested_str(effect),
  be_nested_str(epoch_ms),
  be_nested_str(font),
  be_nested_str(height),
  be_nested_str(hour),
  be_nested_str(hsv),
  be_nested_str(icon),
  be_nested_str(line),
  be_nested_str(line_chart),
  be_nested_str(log),
  be_nested_str(minute),
  be_nested_str(month),
  be_nested_str(now_ms),
  be_nested_str(overlay),
  be_nested_str(pixel),
  be_nested_str(progress),
  be_nested_str(ramp_text),
  be_nested_str(rect),
  be_nested_str(rect_fill),
  be_nested_str(rgb),
  be_nested_str(scroll_text),
  be_nested_str(second),
  be_nested_str(text),
  be_nested_str(text_ink_width),
  be_nested_str(text_width),
  be_nested_str(version),
  be_nested_str(weekday),
  be_nested_str(width),
  be_nested_str(year),
};
