const SYSF={
 wifiSsid:F('wifi','wifi','Wi-Fi network','Pick a network or type its name.'),
 wifiPass:F('wifi','secret','Wi-Fi password','Leave empty to keep the saved password.'),
 hostname:F('wifi','text','Hostname','Name on the network. Empty = automatic.'),
 netStatic:F('wifi','toggle','Static IP','Off = DHCP (recommended).'),
 ip:F('wifi','text','IP address','With the mask, for example 192.168.1.50/24.',
   {showIf:'netStatic',load:(v,d)=>{
     if(!v||!d.subnet)return v;
     const q=(d.subnet.split('.').map(Number).reduce((a,b)=>(a<<8)|b)>>>0);
     const inv=(~q)>>>0;
     if(((inv+1)&inv)!==0)return v;
     return v+'/'+(32-Math.round(Math.log2(inv+1)));
   }}),
 gateway:F('wifi','text','Gateway','Usually your router.',{showIf:'netStatic'}),
 subnet:F('hidden','text','Subnet mask',''),
 dns1:F('wifi','text','DNS 1','Name server, usually your router.',{showIf:'netStatic'}),
 dns2:F('wifi','text','DNS 2','Fallback if the first one does not answer.',{showIf:'netStatic'}),
 wifiConnectTimeout:F('wifi','number','Connect timeout','How long to wait for Wi-Fi at startup before the setup hotspot opens.',{min:5000,max:120000,unit:'ms'}),
 wifiRoamRssi:F('wifi','number','Roam below','Switch access point when the signal stays this weak. 0 = off.',{min:-90,max:0,unit:'dBm'}),
 webPort:F('web','number','Port','Default 80.',{min:1,max:65535}),
 authEnabled:F('web','toggle','Enable login','Ask for a login on this page and the API.'),
 authUser:F('web','text','Username','Needed once a login is required.'),
 authPass:F('web','secret','Password','Leave empty to keep the saved password.',{confirm:true}),
 mqttEnabled:F('mqtt','toggle','Enable MQTT','Connect to the broker below.'),
 mqttHost:F('mqtt','text','Broker host','IP or hostname.'),
 mqttPort:F('mqtt','number','Broker port','1883 on most brokers.',{min:1,max:65535}),
 //linux:begin
 mqttTls:F('mqtt','toggle','TLS','Encrypted, usually port 8883.'),
 mqttTlsPin:F('hidden','text','',''),
 //linux:end
 mqttUser:F('mqtt','text','Username','Leave empty if the broker allows anonymous access.'),
 mqttPass:F('mqtt','secret','Password','Leave empty to keep the saved password.'),
 mqttPrefix:F('mqtt','text','Topic prefix','Empty = device ID.'),
 haDiscovery:F('mqtt','toggle','HA discovery','Announce the device to Home Assistant.'),
 haPrefix:F('mqtt','text','HA prefix','Empty = homeassistant.'),
 ntpServer:F('time','text','NTP server','Time source. Default: pool.ntp.org.'),
 tzName:F('time','tz','Timezone','Daylight saving switches automatically.',
   {derive:v=>({tz:TZRULE.get(v)||'UTC0'})}),
 tz:F('hidden','text','Timezone rule',''),
 panelWidth:F('panel','number','Panel width','Pixels across one panel.',{min:1,max:128,unit:'px'}),
 panels:F('panel','number','Panels','How many panels are chained.',{min:1,max:128}),
 panelStart:F('panel','select','First LED','Corner the data cable arrives at.',{opt:[
   ['topLeft','Top left'],['topRight','Top right'],
   ['bottomLeft','Bottom left'],['bottomRight','Bottom right']]}),
 panelWiring:F('panel','select','Wiring direction','How the strip runs in a panel.',{opt:[
   ['rows','Along the rows'],['columns','Along the columns']]}),
 panelColorOrder:F('panel','select','LED color order','Change it if colors look wrong.',{opt:[
   ['grb','GRB'],['rgb','RGB'],['rbg','RBG'],['gbr','GBR'],['brg','BRG'],['bgr','BGR']]}),
 panelSerpentine:F('panel','toggle','Serpentine','Every second run goes backwards (zigzag).'),
 panelChainReverse:F('panel','toggle','Reverse chain','The cable enters the panels at the other end.'),
 panelChainSerpentine:F('panel','toggle','Alternating panels','Every second panel is upside down.'),
 mirror:F('panel','toggle','Mirror','Flips the picture left to right.'),
 rotate:F('panel','toggle','Rotate 180°','Turns the picture upside down and swaps the left and right buttons.'),
 minBrightness:F('hw','number','Min brightness','Lower limit for auto brightness.',{min:0,max:255}),
 maxBrightness:F('hw','number','Max brightness','Upper limit for auto brightness.',{min:0,max:255}),
 ldrFactor:F('hw','number','LDR factor','Scales the light sensor reading.',{min:0,max:10,step:0.1}),
 ldrGamma:F('hw','number','LDR gamma','Higher = dimmer at moderate light. 1.0 = off.',{min:0.1,max:10,step:0.1}),
 ldrOnGround:F('hw','toggle','LDR on GND','Set if the light sensor is wired to ground.'),
 brightnessSmoothing:F('hw','number','Brightness smoothing','Higher = calmer response to light changes.',{min:0,max:60000,unit:'ms'}),
 batteryDividerRatio:F('hw','number','Battery divider','Only change it if the percentage is wrong.',{min:0.1,max:10,step:0.01}),
 tempOffset:F('hw','number','Temperature offset','Added to the reading. -9 cancels the case heat.',{min:-20,max:20,step:0.1,unit:'°'}),
 humOffset:F('hw','number','Humidity offset','Added to the reading.',{min:-50,max:50,step:0.1,unit:'%'}),
 tempDecimals:F('hw','number','Temperature decimals','Digits after the decimal point.',{min:0,max:2}),
 lowBatteryThreshold:F('hw','number','Low-battery threshold','Warn below this charge. 0 = off.',{min:0,max:100,unit:'%'}),
 swapButtons:F('btn','toggle','Swap buttons','Use it if left and right act the wrong way round.'),
 buttonCallback:F('btn','text','Button webhook','HTTP URL called on button press.'),
 pinMatrix:F('gpio','select','LED data','Data line to the LEDs.',{opt:[2,4,5,13,14,15,16,18,21,25,26,27,32,33].map(p=>[p,'GPIO '+p+(p===32?' (Ulanzi)':'')])}),
 pinBtnLeft:F('gpio','number','Button left','Goes to the previous app.',{min:-1,max:39}),
 pinBtnSelect:F('gpio','number','Button select','Dismisses notifications. Double-press turns the display on or off.',{min:-1,max:39}),
 pinBtnRight:F('gpio','number','Button right','Goes to the next app.',{min:-1,max:39}),
 pinBattery:F('gpio','number','Battery','Battery voltage input.',{min:-1,max:39}),
 pinLdr:F('gpio','number','Light sensor','Light sensor input.',{min:-1,max:39}),
 pinBuzzer:F('gpio','number','Buzzer','Piezo buzzer for tones and melodies.',{min:-1,max:39}),
 pinI2cSda:F('gpio','number','I2C SDA','Sensor bus data.',{min:-1,max:39}),
 pinI2cScl:F('gpio','number','I2C SCL','Sensor bus clock.',{min:-1,max:39}),
 pinDfRx:F('gpio','number','DFPlayer RX','For a DFPlayer module.',{min:-1,max:39}),
 pinDfTx:F('gpio','number','DFPlayer TX','For a DFPlayer module.',{min:-1,max:39}),
 pinI2sBclk:F('gpio','number','I2S BCLK','External DAC for internet radio and MP3s.',{min:-1,max:39}),
 pinI2sLrclk:F('gpio','number','I2S LRCLK','Same DAC, word select.',{min:-1,max:39}),
 pinI2sDout:F('gpio','number','I2S DOUT','Same DAC, data.',{min:-1,max:39}),
 pinI2sMclk:F('gpio','number','I2S MCLK','Only some DACs need it.',{min:-1,max:39}),
 pinAmpEnable:F('gpio','number','Amplifier enable','Switches the amplifier on.',{min:-1,max:39}),
 volume:F('hidden','slider','Master','',{min:0,max:100,api:'settings'}),
 radioVolume:F('hidden','slider','Radio','',{min:0,max:100,api:'settings'}),
 appVolume:F('hidden','slider','Apps','',{min:0,max:100,api:'settings'}),
 alertVolume:F('hidden','slider','Alerts','',{min:0,max:100,api:'settings'}),
 //linux:begin
 bootSound:F('hidden','toggle','Boot sound','Plays when the clock starts.',{api:'settings'}),
 musicSource:F('hidden','select','Music source','What music visualizers react to. Automatic: what plays, otherwise the microphone.',{api:'settings',opt:[['auto','Automatic'],['playback','Playback'],['microphone','Microphone']]}),
 //linux:end
 dfplayer:F('sndhw','toggle','DFPlayer','A DFPlayer module is connected.'),
 statsInterval:F('misc','number','Stats interval','How often status values go out over MQTT.',{min:1000,max:600000,unit:'ms'}),
 artnet:F('misc','toggle','Art-Net','Receive Art-Net DMX on UDP 6454.'),
 mirrorShare:F('share','toggle','Share display',''),
 mirrorShareApps:F('share','text','Shared apps','Comma-separated names. * = all.'),
 mirrorShareNotifications:F('share','toggle','Share notifications',''),
 mirrorFrom:F('share','text','Mirror clock','IP or hostname.'),
 mirrorFromApps:F('share','text','Mirrored apps','Comma-separated names. * = all.'),
 mirrorFromNotifications:F('share','toggle','Mirror notifications',''),
 debugMode:F('misc','toggle','Debug mode','More detail in the log.'),
 scriptingEnabled:F('script','toggle','Run scripts','Off stops all scripts and frees memory. Scripts stay installed. Needs a reboot.'),
};
const SYS_GROUPS=[['wifi','grpWifi','grpWifiH'],['web','grpWeb','grpWebH'],['mqtt','grpMqtt','grpMqttH'],
 ['time','grpTime','grpTimeH'],['panel','grpPanel','grpPanelH'],['hw','grpHw','grpHwH'],
 ['gpio','grpGpio','grpGpioH'],['btn','grpBtn','grpBtnH'],
 ['sndhw','grpSndHw','grpSndHwH'],['script','grpScript','grpScriptH'],['share','grpMirror','grpMirrorH'],
 ['misc','grpMisc','grpMiscH']];
