#pragma once

// Member, NVS key, secret flag, what the field needs from the platform (ConfigNeed). The string is
// the on-flash key: max 15 characters, and renaming one silently drops the stored value on every
// device already in the field.
#define AWTRIX_CFG_FIELDS(X)                   \
  X(wifiSsid, "ssid", 0, None)                 \
  X(wifiPass, "wpass", 1, None)                \
  X(netStatic, "netstatic", 0, None)           \
  X(ip, "ip", 0, None)                         \
  X(gateway, "gw", 0, None)                    \
  X(subnet, "sn", 0, None)                     \
  X(dns1, "dns1", 0, None)                     \
  X(dns2, "dns2", 0, None)                     \
  X(wifiConnectTimeout, "wifitmo", 0, None)    \
  X(wifiRoamRssi, "wifiroam", 0, None)         \
  X(mqttEnabled, "menable", 0, None)           \
  X(mqttHost, "mhost", 0, None)                \
  X(mqttPort, "mport", 0, None)                \
  X(mqttUser, "muser", 0, None)                \
  X(mqttPass, "mpass", 1, None)                \
  X(mqttPrefix, "mprefix", 0, None)            \
  X(haDiscovery, "hadisc", 0, None)            \
  X(haPrefix, "haprefix", 0, None)             \
  X(ntpServer, "ntp", 0, None)                 \
  X(tz, "tz", 0, None)                         \
  X(tzName, "tzname", 0, None)                 \
  X(hostname, "host", 0, None)                 \
  X(webPort, "webport", 0, None)               \
  X(authEnabled, "aenable", 0, None)           \
  X(authUser, "auser", 0, None)                \
  X(authPass, "apass", 1, None)                \
  X(tempOffset, "tempoff", 0, None)            \
  X(humOffset, "humoff", 0, None)              \
  X(batteryDividerRatio, "batdiv", 0, None)    \
  X(lowBatteryThreshold, "lowbat", 0, None)    \
  X(minBrightness, "minbri", 0, None)          \
  X(maxBrightness, "maxbri", 0, None)          \
  X(ldrFactor, "ldrfac", 0, None)              \
  X(ldrGamma, "ldrgam", 0, None)               \
  X(ldrOnGround, "ldrgnd", 0, None)            \
  X(brightnessSmoothing, "brismooth", 0, None) \
  X(panelWidth, "pw", 0, Panel)                \
  X(panels, "pnc", 0, Panel)                   \
  X(panelStart, "pstart", 0, Panel)            \
  X(panelWiring, "pwire", 0, Panel)            \
  X(panelColorOrder, "pcolor", 0, Panel)       \
  X(panelSerpentine, "pserp", 0, Panel)        \
  X(panelChainReverse, "pchrev", 0, Panel)     \
  X(panelChainSerpentine, "pchserp", 0, Panel) \
  X(mirror, "mirror", 0, Panel)                \
  X(rotate, "rotate", 0, Panel)                \
  X(swapButtons, "swapbtn", 0, None)           \
  X(dfplayer, "dfplayer", 0, None)             \
  X(buttonCallback, "btncb", 0, None)          \
  X(artnet, "artnet", 0, None)                 \
  X(mirrorShare, "mirshare", 0, None)          \
  X(mirrorShareApps, "mirshapps", 0, None)     \
  X(mirrorShareNotifications, "mirshnote", 0, None) \
  X(mirrorFrom, "mirfrom", 0, None)            \
  X(mirrorFromApps, "mirfrapps", 0, None)      \
  X(mirrorFromNotifications, "mirfrnote", 0, None) \
  X(statsInterval, "statsint", 0, None)        \
  X(tempDecimals, "tempdec", 0, None)          \
  X(debugMode, "dbg", 0, None)                 \
  X(scriptingEnabled, "scren", 0, None)        \
  X(pinMatrix, "pmatrix", 0, Gpio)             \
  X(pinBtnLeft, "pbtnl", 0, Gpio)              \
  X(pinBtnSelect, "pbtns", 0, Gpio)            \
  X(pinBtnRight, "pbtnr", 0, Gpio)             \
  X(pinBattery, "pbat", 0, Gpio)               \
  X(pinLdr, "pldr", 0, Gpio)                   \
  X(pinBuzzer, "pbuzz", 0, Gpio)               \
  X(pinI2cSda, "psda", 0, Gpio)                \
  X(pinI2cScl, "pscl", 0, Gpio)                \
  X(pinDfRx, "pdfrx", 0, Gpio)                 \
  X(pinDfTx, "pdftx", 0, Gpio)                 \
  X(pinI2sBclk, "pi2sbck", 0, Gpio)            \
  X(pinI2sLrclk, "pi2slrc", 0, Gpio)           \
  X(pinI2sDout, "pi2sdo", 0, Gpio)             \
  X(pinI2sMclk, "pi2smck", 0, Gpio)            \
  X(pinAmpEnable, "pampen", 0, Gpio)
