const STR={
  skip:'Skip to content',mainnav:'Main navigation',dash:'Dashboard',display:'Display',system:'System',icons:'Icons',palettes:'Palettes',log:'Log',
  audioTab:'Audio',
  mp3s:'MP3s',
  mp3shelp:'Your own MP3s, then the sounds that came with scripts.',
  mp3find:'Search sounds',mp3nohit:'No matching sounds',mp3n:'sounds',
  sndOwner:'Sure? Used by {s}',sndOrphan:'script removed',delSndAsk:'{s} has its own sounds ({n}).',delWithSnd:'Delete with sounds',keepSnd:'Keep sounds',sndLink:'Sounds ({n})',sndAdd:'Add sounds',sndNoScript:'The script is no longer on the clock.',
  sndRestart:'Restart {s} to hear its sounds.',
  sndNoMp3:'Not an MP3 file.',sndName:'Rename it: only letters, digits, _ and -, up to 32 characters.',sndFull:'Not enough space on the clock.',sndClash:'A sound with that name already exists',sndDl:'Could not download {f} from the Hub.',
  sndRoom:'Not enough space: the sounds need {n}, {f} free.',
  sndOff:'Sounds skipped: this clock cannot play MP3s.',sndStep:'Sound {i} of {n}: {f}',
  sndInst:'Installing {s}…',sndDel:'Removing old sounds…',retry:'Try again',
  fitSave:'Save anyway',fitImport:'Import anyway',
  nowon:'On the clock',nowidle:'Nothing playing',
  radioTab:'Radio',
  radioH:'Internet radio stations.',
  radionone:'No stations yet. Add one below.',
  radioname:'Name',radiourl:'Stream URL',
  radioadd:'Add station',
  radiodupe:'name already in use',radiobadurl:'must start with http:// or https://',

  appsTab:'Apps',apploop:'On the display',apploopH:'Shown in turn. Drag ⠿ to reorder.',
  background:'In the background',backgroundH:'Always running, never shown.',
  ondemandapps:'In the device menu',ondemandH:'On the clock, hold the middle button and choose Scripts. Hold again to stop.',start:'Start',started:'Starting…',
  disabledapps:'Switched off',disabledH:'Not running.',
  sharedcfg:'Shared settings',sharedcfgH:'Used by several scripts.',
  switchto:'Show',more:'Actions',dupapp:'Duplicate',moveUp:'Move up',moveDown:'Move down',
  noapps:'No apps',dragord:'Drag to reorder',
  kindBuiltin:'Built-in',kindScript:'Script',kindPushed:'Pushed',kindModule:'Module',
  appRuns:'Run {n}',appOn:'{n} switched on',appOff:'{n} switched off',
  undo:'Undo',undone:'Undone',
  chipErr:'error',chipFit:'does not fit',chipRun:'running',chipRunH:'On the display now.',
  chipSkip:'skipped',chipSkipH:'Skipped this round. It stays in the rotation.',
  chipGone:'no data',chipGoneH:'No data yet. Shows again with the next update.',
  orderSaved:'Saved',
  modules:'Modules',modulesH:'Code that other scripts load with import.',
  modnone:'No modules yet',
  suCheck:'Check for updates',suChecking:'Checking for updates…',suReady:'Update available',suCurrent:'Up to date',suLocal:'Changed on the clock',suMissing:'No longer available on the Hub',suOffline:'Hub not reachable',suUpdate:'Update script',suCopy:'Install as a new script',suConfirm:'Install this version from the Hub? Your settings are kept.',suModified:'You changed this script. Install the Hub version as a new script to keep your changes.',suBusy:'Updating script…',suDone:'Script updated',suFirmware:'Update the firmware to get script updates.',suChanged:'The script changed. Check for updates again.',suIntegrity:'The Hub version changed during download. Try again.',suUnknown:'Not checked yet',
  suRevision:'Hub version',
  reqNeeds:'{s} needs:',reqHub:'installs from the Hub',reqSelf:'missing, install it yourself',reqGone:'not on the Hub, install it yourself',reqWith:'Install all',reqOnly:'Only this script',reqDone:'Installed {s} with {d}',reqGot:'Installed {d}',reqLeft:'Still missing:',reqFail:'{d} could not be installed:',reqMissing:'Missing:',reqInstall:'Install',
  cfgTitle:'Settings',cfgHide:'Close settings',cfgLoading:'Loading settings…',cfgNone:'No settings.',
  cfgSaved:'Saved. The app restarted.',cfgSavedBuiltin:'Saved',cfgDefaults:'Reset to defaults',
  cfgInherit:'Global text color',cfgGroupTime:'Time',cfgGroupDate:'Date',cfgGroupCalendar:'Calendar & date',cfgGroupWeekday:'Weekday bar',
  cfgWarnH:'The settings block of this script has an error. Fix it in the editor.',
  save:'Save',saved:'Saved',sure:'Sure?',cancel:'Cancel',del:'Delete',edit:'Edit',
  discard:'Discard',unsaved:'unsaved changes',choose:'Choose file…',
  upload:'Upload',uploaded:'uploaded',
  neterr:'Clock not reachable',power:'Power',brightness:'Brightness',prevapp:'Previous app',nextapp:'Next app',rotpause:'Pause app rotation',rotplay:'Resume app rotation',
  dismiss:'Dismiss notification',dismissed:'Notification dismissed',
  snap:'Save screenshot',rec:'Record GIF',recstop:'Stop and save GIF',
  livepre:'Live preview',version:'Version',host:'Hostname',ip:'IP address',wifi:'Wi-Fi',uptime:'Uptime',ram:'Free memory',psram:'PSRAM',
  psramnone:'none',
  battery:'Battery',light:'Light level',temp:'Temperature',hum:'Humidity',curapp:'Current app',
  excellent:'excellent',good:'good',fair:'fair',weak:'weak',
  advanced:'Advanced',advhelp:'Settings without their own form. Change with care.',
  rebootreq:'Saved. Reboot to apply.',rebootnow:'Reboot now',rbclose:'Dismiss',
  rebooting:'Rebooting… The page reloads by itself.',reboot:'Reboot',
  apbanner:'Setup mode: connect the clock to your Wi-Fi below.',
  scan:'Scan',scanning:'Scanning…',networks:'networks found',
  maint:'Maintenance',mainthelp:'Firmware updates and resets.',
  apmaintH:'Reboot to apply the saved Wi-Fi settings.',
  fwfile:'Upload firmware (.bin)',
  update:'Firmware update',updchk:'Check for updates',updchecking:'Checking for updates…',
  updcur:'{v} is the latest version.',updnew:'{v} is available',updfail:'Could not check for updates. Try again later.',updrate:'Too many update checks from this network. Try again later.',
  updnotes:'Release notes',updavail:'update available',
  updinstall:'Download & install',upddownloading:'Downloading firmware…',upduploading:'Uploading firmware…',updnotready:'This release is not ready to download yet. Try again later or upload the file.',updbadfile:'Download check failed. Nothing was installed. Try again.',updbusy:'A firmware update is already running.',
  resetset:'Reset settings',resetsetH:'Display settings back to defaults. Network settings stay.',
  factory:'Factory reset',factoryH:'Erases everything: Wi-Fi, files and settings. Type the hostname to confirm.',
  erase:'Erase everything',eraseNo:'Hostname does not match',
  bkSection:'Backup & restore',bkSectionH:'Download a ZIP of what you choose, or restore one.',
  bkSectionAp:'Restore',
  bkTitle:'Create backup',bkDownload:'Download backup',bkDownloadH:'Pick what to include, then save a .zip.',
  bkWorking:'Collecting…',bkDone:'Backup downloaded',bkAll:'All',
  bkWifi:'Wi-Fi',bkSettings:'Settings',bkIcons:'Icons',bkMelodies:'Melodies',bkPalettes:'Palettes',bkMp3:'MP3s',bkScripts:'Scripts',bkApporder:'App order',
  bkRestoreT:'Restore backup',bkRestore:'Choose backup…',
  bkRestoreH:'Upload a backup .zip.',
  bkCaptiveHint:'The Wi-Fi sign-in window can\'t upload files. To restore, open this page in a browser:',
  bkRestored:'Backup restored',bkWarnings:'warning(s)',bkRebootQ:'Restored. Reboot now?',
  of:'of',free:'free',
  editorTab:'Icon Editor',
  edLoading:'Loading the editor…',
  edUnreachable:'The editor could not load.',
  edIconOpenError:'The icon could not be opened.',
  edLiveSize:'Too large for Live.',edLiveColors:'Too many colors for Live.',
  edLiveKeep:'The clock keeps the last frame that fit.',
  edLiveStill:'Animation too large for Live. The clock shows the current frame.',
  melodies:'Melodies',melodieshelp:'Ringtones for notifications and scripts.',
  newmelo:'New melody',meloname:'Name',melortttl:'d=4,o=5,b=120:c,e,g',
  melopre:'Play in browser',meloprestop:'Stop',meloplay:'Play on the clock',melostop:'Stop on the clock',
  mixer:'Mixer',
  audnone:'No sound output. Set a buzzer or speaker pin under System › GPIO.',
  melonone:'No melodies yet',
  melonotes:'notes',melobroken:'Invalid melody',
  meloexists:'A melody with this name already exists',
  melobadname:'Name: letters, digits, _ and -, up to 24 characters',
  idbnone:"No matching icons",idbfail:'Hub not reachable. Check your internet connection.',
  idbterms:"By publishing, you agree to the terms of service.",
  hubConnect:'Connect to Hub',hubStorageFail:'Could not save the key. Allow this site to store data and try again.',
  hubIconUnavailable:"This icon is no longer available on the Hub.",hubDownloadFailed:'Download failed. Try again.',hubPublishFailed:'Publishing failed. Try again.',hubPublishing:"Publishing…",
  hubSection:'AWTRIX Hub',hubSectionH:'Connect your Hub account to get icons and script updates and to share icons.',
  hubAuthRequired:"Connect your Hub account to download from the Hub.",hubAuthRejected:"The Hub did not accept this key. Check it or add a new one.",hubWrongHost:"This icon comes from a different Hub. Open its Hub page to download it.",hubTokenLbl:"Hub connection key",hubTokenH:'Saved in this browser only.',
  hubOn:'Key saved',hubOff:"No key saved",hubClear:"Remove key",hubCleared:"Hub key removed from this browser.",hubStored:"Hub key saved in this browser.",
  hubGetLbl:"Get a connection key",hubGetH:"Copy your key from your Hub account settings.",hubGet:"Open Hub account",
  icfromhub:'From the Hub',icmodified:'Changed on the clock',icchecking:"Checking Hub status…",icunknown:'Hub not reachable',
  icviewhub:'View on Hub',icvariant:"Share as a new icon",
  icoriginfail:'The icon is on the clock but not linked to the Hub. Install it again.',
  icconflict:'Another icon on the clock has this name:',
  icpubname:"Icon name",icpubexample:'Sunny sky',
  icpubnamehelp:'A descriptive name with letters, not just numbers.',
  scricons:'Install icons',scriconsok:"Icons ready",
  scriconserr:"These icons could not be installed:",idbsend:'Publish',
  icintro:"Choose icons for your display or create your own.",icsearch:'Search installed icons',icclear:'Clear search',icstorage:'Storage',icdownload:"Download icon",
  icupload:"Add icon",icuploadhelp:"Choose an image from your computer. Animated GIFs stay animated.",icdrop:'Choose files or drop them here · GIF, PNG or JPG',ichub:"Find icons in the Hub",ichubhelp:'Browse community icons and send them to this clock.',ichubopen:"Icons for this device",iccreate:"Create an icon",iccreatehelp:'Draw an icon or animation for the clock.',
  icown:'On the clock',icclash:'An icon with that name already exists',icadd:'Add',icnone:'No icons yet',icsend:'Publish to Hub',icshow:'Show on the clock',
  idbdone:"Your icon is now published on the Hub.",idbopen:"View icon",
  idbdup:"This icon is already on the Hub as",
  close:'Close',
  // One entry per error code the submit endpoint can answer with. tooManyFrames
  // is never sent - frames are not a limit. Unknown codes use a readable fallback.
  idbe_badFormat:"This image could not be read. Try another file.",
  idbe_tooLarge:"The image must be no larger than 64 KB.",
  idbe_badName:'This name cannot be used. Choose another.',
  idbe_descriptiveNameRequired:'Use a name with letters, such as “Sunny sky”.',
  idbe_tooBig:'This image is too large for the Hub.',
  idbe_rateLimited:"Too many attempts. Wait a moment and try again.",
  idbe_duplicate:"This icon is already on the Hub.",
  idbe_notLoggedIn:"Connect your Hub account to publish this icon.",
  scriptsTab:'Scripts',
  scrHubFind:'Scripts for this device',
  capGamepad:'a gamepad',capBle:'Bluetooth',capEffect:'layered sound',capSong:'the synthesizer',capMic:'a microphone',capSpeech:'speech output',capMp3:'MP3 playback',
  capRadio:'web radio',capRtttl:'melodies',capTrack:'a DFPlayer',capLight:'a light sensor',capOauth:'sign-in to services',capCrypto:'crypto functions',capTcp:'TCP connections',capPanel:'a {w}×{h} panel',
  fitNeeds:'Not for this clock: needs {w}.',reqNoFit:'needs {w}',suNoFit:'This version needs {w}.',
  recNative:'Original size, one pixel per LED. For the Hub.',
  scrnone:'Nothing open',
  scrkeys:'Ctrl-. API · Ctrl-S save · Ctrl-/ comment',
  newscr:'New from template',import:'Import',export:'Export',
  newmod:'New module from template',
  scrbadname:'Name: letters, digits, _ and -, up to 32 characters',
  rename:'Rename',renamed:'Renamed',scrnolist:'No scripts yet',
  sharedHead:'Shared',shnone:'No values yet',
  shhelp:'Values that scripts share with shared.set(). Cleared on reboot.',
  scrclash:'A script with that name already exists',
  scrempty:'The editor is empty',
  scrok:'Running',scrbroken:'Saved, but the script has an error',
  scroffTitle:'Scripts are switched off',
  scroffGo:'Turn on',
  appsscroff:'Scripts are switched off.',
  scrimported:'imported into the editor',
  scrpreview:'Show on the clock',scrpreviewed:'Now on the clock',
  scrline:'Ln',scrreload:'Reloaded',
  scrcode:'Code',scrdata:'Data',dataobj:'The data must be a JSON object { … }',datafix:'Invalid JSON. Fix the marked line.',
  scrinhook:'runtime error in',
  palhelp:'Color gradients for effects, text, charts and progress bars.',
  paledit:'Palette editor',name:'Name',tryit:'Try on the clock',newpal:'New palette',
  palsaved:'Palette saved',palname:'Letters and digits only',
  palbuiltin:'Built-in',palyours:'Yours',palnone:'No palettes of your own yet',
  paloverr:'edited',paldup:'Duplicate',palreset:'Restore original',
  palrestored:'Original restored',palstops:'stops',palstop:'Stop',
  paladd:'Add stop',palrmstop:'Remove stop',palfull:'A palette holds up to 16 stops.',
  palstopcol:'Stop color',palstoppos:'at',paleven:'Spread evenly',
  palbad:'Unreadable. The clock cannot use this palette.',
  palblend:'Blend',palblendh:'Preview only. Each app sets its own blend.',
  palsaveas:'Save as new',paloverride:'Replace built-in',
  palunsaved:'Unsaved changes to this palette.',
  palwillover:'built-in palette. Saving replaces it.',
  palownhelp:'A new name saves a copy and keeps this one.',
  loghelp:'Live log of the clock.',
  clear:'Clear',copy:'Copy',copied:'Copied',autoscroll:'Auto-scroll',
  deleted:'Deleted',playing:'Playing',shown:'Shown on the clock',
  nofiles:'No files yet',
  grpBright:'Brightness',grpBrightH:'How bright the display is.',
  grpApps:'App rotation',grpAppsH:'Which apps show is set in the Apps tab.',
  grpText:'Text',grpTextH:'How text looks and scrolls.',
  grpOverlay:'Weather overlay',grpOverlayH:'A weather effect over every app.',
  grpColor:'Color',grpColorH:'Color tuning for the whole display.',
  grpWifi:'Wi-Fi',grpWifiH:'Changes need a reboot.',
  grpWeb:'Web server',grpWebH:'Port and login for this page.',
  grpMqtt:'MQTT',grpMqttH:'Broker connection.',
  mqStatus:'Connection',mqStatusH:'Current state.',
  mqoff:'Off',mqdown:'Not connected',mqbusy:'Connecting…',mqup:'Connected',
  grpMirror:'Mirroring',grpMirrorH:'Show one clock on another of the same size.',miStatus:'State',miShared:'Viewers',
  mioff:'Off',mioffline:'No network',miresolving:'Searching…',minotFound:'Clock not found',
  miwaiting:'No answer',miidle:'Nothing shared',mifiltered:'App not selected',
  misizeMismatch:'Other display size',minoMemory:'Out of memory',mishowing:'Mirroring',
  //linux:begin
  gpNone:'No gamepad paired',gpPair:'Add gamepad',gpPairH:'Put the gamepad in pairing mode, then press Pair.',gpPairBtn:'Pair',gpForget:'Forget',gpPhone:'Phone',
  gpDevice:'Controller',gpPlayer:'Player',gpFull:'Forget a controller to add another.',
  vcSection:'Home Assistant Voice',vcSectionH:'Hold the knob, speak, let go.',
  vcOn:'Voice',vcOnH:'Off: the knob does nothing.',vcUrl:'Address',
  vcToken:'Token',vcTokenH:'Long-lived token from your HA profile.',
  vcTokenSet:'Saved',vcTokenNone:'None',vcTokenKeep:'Empty keeps it',vcTokenClear:'Remove',
  vcPipe:'Pipeline',vcPipeH:'Needs STT and TTS.',vcPipeDef:'Default',vcSave:'Save and connect',
  vcDev:'Room device',vcDevH:'Address of an HA device page. Its area is the room for "turn on the lights".',vcDevP:'Optional',
  vcoffline:'Off',vcconnecting:'Connecting…',vcready:'Ready',vcstarting:'Starting…',vclistening:'Listening',
  vcprocessing:'Thinking…',vcspeaking:'Speaking',vcerror:'Error',
  vceconnectionLost:'HA unreachable',vcetokenRejected:'Token rejected',vcehaError:'HA error',
  vcepipelineIncomplete:'Pipeline lacks STT/TTS',vcenothingUnderstood:'Not understood',vceaudioTooSlow:'Wi-Fi too slow',
  vcetimeout:'HA too slow',vcemicrophoneFailed:'Microphone error',vceplaybackFailed:'Playback error',
  vcemicrophoneUpdate:'Microphone update pending',vceconfigUnavailable:'Settings unreadable',
  vcfurl:'Address only, no path',vcftoken:'Enter token again',vcfpipeline:'Pick a pipeline',vcfdevice:'Not a device address',vcfenabled:'Needs address and token',
  ipOn:'iPhone link',ipOnH:'Then pair the clock on the iPhone under Settings › Bluetooth.',ipWait:'Waiting for iPhone',
  ipForget:'Forget iPhone',ipForgot:'Also forget the clock on the iPhone.',
  oaSection:'Sign-in',oaStatus:'Status',oaId:'Client ID',oaSecret:'Client secret',oaKeep:'Saved – type to replace',
  oaSecretPkce:'Not every provider needs one.',
  oaSignIn:'Sign in',oaSignOut:'Sign out',oaDone:'Signed in',oaInvalid:'@oauth line invalid',
  oasignedIn:'Signed in',oasignedOut:'Not signed in',oapending:'Signing in…',oaerror:'Sign-in failed',
  //linux:end
  mqRetry:'retry in',
  mqeNoWifi:'No Wi-Fi',mqeHost:'Host not found',mqeRefused:'Refused',
  mqeAuth:'Wrong login',mqeRejected:'Broker refused',mqeTimeout:'No response',mqeLost:'Lost',
  grpTime:'Time',grpTimeH:'Time server and timezone.',
  tzDetect:'Use my zone',tzDetectH:'Use this browser’s timezone.',
  tzDstOn:'daylight saving active',tzDstOff:'standard time',tzNoDst:'no daylight saving',
  tzNext:'next change',tzUnknown:'This browser reports a zone the clock does not know:',
  grpPanel:'Panel',grpPanelH:'How your LED panels are wired. All but the total width apply at once.',
  pnSize:'Display size',pnSizeH:'Set by the fields below.',
  pnLeds:'LEDs',pnPanelsOf:'panels of',pnOne:'one panel',
  pnBadWidth:'The total width must be between 32 and 128.',
  grpHw:'Brightness & sensors',grpHwH:'Auto-brightness limits and sensor calibration.',
  grpGpio:'GPIO',grpGpioH:'Which pin does what. Applies after a reboot.',
  preset:'Preset wiring',presetH:'Fills the fields with a known board’s wiring.',
  presetUlanzi:'Ulanzi TC001',presetAwtrix2:'AWTRIX 2 mainboard',
  presetApplied:'Preset filled in. Check and save.',
  pinUsed:'in use',optStored:'stored value',
  wakeNo:'Cannot wake the clock from deep sleep. Only the sleep timer can.',
  grpBtn:'Buttons',grpBtnH:'The buttons on the clock.',
  grpSndHw:'Audio',grpSndHwH:'Audio hardware and sound options.',
  grpScript:'Scripting',grpScriptH:'Berry scripts on the clock.',
  grpMisc:'Misc',grpMiscH:'Everything else.',
};
const t=k=>STR[k]||k;
