#pragma once

#include "../contract/deploy_token.h"
#include "../contract/tc002_layout.h"

#ifndef AWTRIX_LOADER_DATA_DIR
#define AWTRIX_LOADER_DATA_DIR TC002_DATA_DIR
#endif
#ifndef AWTRIX_LOADER_RUNTIME_DIR
#define AWTRIX_LOADER_RUNTIME_DIR TC002_VOLATILE_DIR
#endif
#ifndef AWTRIX_LOADER_PROC_MTD
#define AWTRIX_LOADER_PROC_MTD "/proc/mtd"
#endif
#ifndef AWTRIX_LOADER_MTD_DIR
#define AWTRIX_LOADER_MTD_DIR TC002_MTD_DIR
#endif
#ifndef AWTRIX_LOADER_MTD_BLOCK_DIR
#define AWTRIX_LOADER_MTD_BLOCK_DIR TC002_MTD_BLOCK_DIR
#endif
#ifndef AWTRIX_LOADER_LOOP_MODULE
#define AWTRIX_LOADER_LOOP_MODULE TC002_LOOP_MODULE
#endif
#ifndef AWTRIX_LOADER_PANEL_SPI
#define AWTRIX_LOADER_PANEL_SPI TC002_PANEL_SPI
#endif
#ifndef AWTRIX_LOADER_GPIO_DIR
#define AWTRIX_LOADER_GPIO_DIR "/sys/class/gpio"
#endif
#ifndef AWTRIX_LOADER_VENDOR_LIBRARY
#define AWTRIX_LOADER_VENDOR_LIBRARY "/res/lib/libzkgui.so"
#endif
#ifndef AWTRIX_LOADER_INPUT_DIR
#define AWTRIX_LOADER_INPUT_DIR "/dev/input"
#endif
#ifndef AWTRIX_LOADER_SETPROP
#define AWTRIX_LOADER_SETPROP "/bin/setprop"
#endif
#ifndef AWTRIX_LOADER_UPGRADE_DIR
#define AWTRIX_LOADER_UPGRADE_DIR "/mnt/storage"
#endif
#ifndef AWTRIX_LOADER_USB_ROLE
#define AWTRIX_LOADER_USB_ROLE TC002_USB_ROLE
#endif
#ifndef AWTRIX_LOADER_IDLE_SHELL
#define AWTRIX_LOADER_IDLE_SHELL "/bin/sh"
#endif
#ifndef AWTRIX_LOADER_SETTLE_MS
#define AWTRIX_LOADER_SETTLE_MS 500
#endif
#ifndef AWTRIX_LOADER_USB_CHECK_MS
#define AWTRIX_LOADER_USB_CHECK_MS 2000
#endif
#ifndef AWTRIX_LOADER_DEPLOY_CHECK_MS
#define AWTRIX_LOADER_DEPLOY_CHECK_MS 1000
#endif
#ifndef AWTRIX_LOADER_USB_RETRY_TICKS
#define AWTRIX_LOADER_USB_RETRY_TICKS 5
#endif
#ifndef AWTRIX_LOADER_DEPLOY_STALE_SECONDS
#define AWTRIX_LOADER_DEPLOY_STALE_SECONDS AWTRIX_DEPLOY_TOKEN_STALE_SECONDS
#endif
#ifndef AWTRIX_LOADER_DEPLOY_HOLD_LIMIT_SECONDS
#define AWTRIX_LOADER_DEPLOY_HOLD_LIMIT_SECONDS AWTRIX_DEPLOY_HOLD_SECONDS
#endif

#define LOADER_RELEASE_MOUNT AWTRIX_LOADER_RUNTIME_DIR TC002_RELEASE_MOUNT
#define LOADER_RELEASE_DAEMON LOADER_RELEASE_MOUNT TC002_RELEASE_DAEMON
#define LOADER_STATE_DIR AWTRIX_LOADER_DATA_DIR TC002_STATE
#define LOADER_ATTEMPTS_FILE AWTRIX_LOADER_DATA_DIR TC002_BOOT_ATTEMPTS
#define LOADER_DURABLE_LOG LOADER_STATE_DIR "/loader.log"
#define LOADER_RUNTIME_ATTEMPTS_FILE AWTRIX_LOADER_RUNTIME_DIR TC002_VOLATILE_BOOT_ATTEMPTS
#define LOADER_RUNTIME_LOG AWTRIX_LOADER_RUNTIME_DIR TC002_LOADER_LOG
#define LOADER_VENDOR_MARKER AWTRIX_LOADER_RUNTIME_DIR TC002_VENDOR_MARKER
#define LOADER_RESCUE_MARKER AWTRIX_LOADER_RUNTIME_DIR TC002_RESCUE_MARKER
#define LOADER_DEPLOY_TOKEN AWTRIX_LOADER_RUNTIME_DIR TC002_DEPLOY_TOKEN
#define LOADER_KEYS_DEVICE_NAME TC002_KEYS_DEVICE_NAME
#define LOADER_USB_DEVICE_ROLE TC002_USB_DEVICE_ROLE
#define LOADER_RESCUE_LOG_LINES 64
#define LOADER_DURABLE_LOG_LIMIT 8192
#define LOADER_RUNTIME_LOG_LIMIT 16384
