#!/usr/bin/env python3
"""Generate package constants for Python, JavaScript, C++ and Rust."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = Path(__file__).with_name("constants.json")


def outputs():
    values = json.loads(SOURCE.read_text(encoding="utf-8"))
    entries = [("MAX_ARCHIVE_BYTES", "maxArchiveBytes"), ("MAX_FILE_BYTES", "maxFileBytes"),
               ("MAX_FILES", "maxFiles"), ("RES_PARTITION_BYTES", "resPartitionBytes"),
               ("RES_ERASE_BYTES", "resEraseBytes"), ("RES_CHUNK_BYTES", "resChunkBytes"),
               ("TMP_RESERVE_BYTES", "tmpReserveBytes"), ("MAX_CONFIG_BYTES", "maxConfigBytes"),
               ("USB_CONNECT_WAIT_MS", "usbConnectWaitMs"), ("USB_CONNECT_POLL_MS", "usbConnectPollMs"),
               ("USB_CONNECT_SETTLE_MS", "usbConnectSettleMs"),
               ("USB_CONNECT_STABLE_MS", "usbConnectStableMs"), ("USB_SCAN_END_MS", "usbScanEndMs")]
    for _, key in entries:
        if type(values[key]) is not int or not 0 < values[key] < 1 << 32:
            raise ValueError(f"invalid {key}")
    target = values["productionTarget"]
    if not isinstance(target, str) or not target.isascii() or not target:
        raise ValueError("invalid productionTarget")
    entries.append(("PRODUCTION_TARGET", "productionTarget"))
    notice = "Generated by tools/tc002/install/gen_constants.py from constants.json."
    encoded = [(name, json.dumps(values[key])) for name, key in entries]
    return {
        "tools/tc002/install/constants.py": "# " + notice + "\n" +
            "".join(f"{name} = {value}\n" for name, value in encoded),
        "docs/assets/tc002/constants.js": "// " + notice + "\n" +
            "".join(f"export const {name} = {value};\n" for name, value in encoded),
        "src/platform/tc002/update/PackageConstants.h": "// " + notice + "\n#pragma once\n\n" +
            "namespace awtrix::tc002::update {\n" +
            f"inline constexpr const char* kProductionTarget = {json.dumps(target)};\n" + "}\n",
        "tools/tc002/desktop/native/src/constants.rs": "// " + notice + "\n" +
            f"pub const MAX_ARCHIVE_BYTES: usize = {values['maxArchiveBytes']};\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Run python tools/tc002/install/gen_constants.py: " + ", ".join(stale))
    print("TC002 package constants are current")


if __name__ == "__main__":
    main()
