if(NOT ${TC002_PREFIX_VARIABLE})
  set(${TC002_PREFIX_VARIABLE} "$ENV{${TC002_PREFIX_VARIABLE}}" CACHE FILEPATH "Prefix of the TC002 cross compiler")
endif()
set(TC002_COMPILER_PREFIX "${${TC002_PREFIX_VARIABLE}}")
if(NOT EXISTS "${TC002_COMPILER_PREFIX}gcc")
  message(FATAL_ERROR "${TC002_PREFIX_VARIABLE} names no compiler (${TC002_COMPILER_PREFIX}gcc); "
                      "see tools/tc002/toolchain/env.sh")
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ${TC002_PREFIX_VARIABLE})

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(CMAKE_C_COMPILER "${TC002_COMPILER_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${TC002_COMPILER_PREFIX}g++")
execute_process(COMMAND "${CMAKE_C_COMPILER}" -print-sysroot
                OUTPUT_VARIABLE TC002_SYSROOT OUTPUT_STRIP_TRAILING_WHITESPACE
                COMMAND_ERROR_IS_FATAL ANY)
set(CMAKE_FIND_ROOT_PATH "${TC002_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(PKG_CONFIG_EXECUTABLE "" CACHE FILEPATH "pkg-config, unused for the TC002")
