
import gzip
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile

try:
    Import("env")
except NameError:
    env = None

# Firmware and Hub update controls share the embedded UI; allow their bounded growth.
BUDGET = 92 * 1024

# Code that only the Linux runtime can use (awtrix-linux, TC002) sits in webui/index.html between
# two marker lines, each alone on its line apart from indentation:
#
#     //linux:begin
#     ...
#     //linux:end
#
# The markers are JavaScript line comments, so they may stand wherever a comment may: between
# statements, functions or the properties of an object literal (such as the STR table), but not
# in HTML or CSS. Regions do not nest. awtrix-linux serves the file as it is. WebUiAsset.h holds
# two minified, gzipped streams: WEBUI_GZ, which the ESP32 firmware compiles, drops each region
# with its markers; WEBUI_FULL_GZ keeps the regions and drops only the marker lines. It sits under
# AWTRIX_WEBUI_FULL, which no firmware build defines, and tools/tc002/install/bundle.py ships it
# as the TC002 web UI.
LINUX_BEGIN = "//linux:begin"
LINUX_END = "//linux:end"


class MarkerError(ValueError):
    pass


def strip_linux_only(text, keep_regions=False):
    kept = []
    begin = None
    for number, line in enumerate(text.splitlines(keepends=True), 1):
        marker = line.strip()
        if marker not in (LINUX_BEGIN, LINUX_END):
            if LINUX_BEGIN in line or LINUX_END in line:
                raise MarkerError("line %d: a Linux-only marker must stand alone on its line" % number)
            if begin is None or keep_regions:
                kept.append(line)
        elif marker == LINUX_BEGIN:
            if begin is not None:
                raise MarkerError("line %d: %s inside the region opened on line %d"
                                  % (number, LINUX_BEGIN, begin))
            begin = number
        else:
            if begin is None:
                raise MarkerError("line %d: %s without %s" % (number, LINUX_END, LINUX_BEGIN))
            begin = None
    if begin is not None:
        raise MarkerError("line %d: %s is never closed by %s" % (begin, LINUX_BEGIN, LINUX_END))
    return "".join(kept)


MINIFIER = "html-minifier-terser@7.2.0"
MINIFY_ARGS = [
    "--collapse-whitespace",
    "--conservative-collapse",
    "--remove-comments",
    "--minify-css",
    "true",
    "--minify-js",
    "true",
]
FULL_GUARD = "AWTRIX_WEBUI_FULL"


def refresh_source():
    import webui_source

    if webui_source.write(env["PROJECT_DIR"]):
        print("webui: assembled webui/index.html")


def minify(html):
    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx:
        raise SystemExit(
            "webui: npx (Node.js) not found on PATH, and the web UI is minified with "
            "%s before it is embedded. Install Node.js, or run the build with an "
            "already-populated npx cache." % MINIFIER
        )
    fd, src = tempfile.mkstemp(suffix=".html")
    with os.fdopen(fd, "wb") as f:
        f.write(html)
    fd, tmp = tempfile.mkstemp(suffix=".html")
    os.close(fd)
    try:
        proc = subprocess.run(
            [npx, "--yes", MINIFIER] + MINIFY_ARGS + ["-o", tmp, src],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        if proc.returncode != 0:
            raise SystemExit(
                "webui: %s failed (exit %d):\n%s"
                % (MINIFIER, proc.returncode, proc.stdout.decode("utf-8", "replace"))
            )
        with open(tmp, "rb") as f:
            return f.read()
    finally:
        os.remove(src)
        os.remove(tmp)


def gz_array(name, gz):
    lines = [
        'inline constexpr char %s_ETAG[] = "\\"%s\\"";' % (name, hashlib.md5(gz).hexdigest()),
        "inline constexpr unsigned %s_GZ_LEN = %d;" % (name, len(gz)),
        "inline const uint8_t %s_GZ[] PROGMEM = {" % name,
    ]
    for i in range(0, len(gz), 20):
        lines.append("    " + "".join("0x%02x," % b for b in gz[i : i + 20]))
    return lines + ["};"]


def render_header(raw, mini, gz, full_mini, full_gz):
    lines = [
        "#pragma once",
        "// GENERATED by scripts/build_webui.py from webui/index.html - DO NOT EDIT.",
        "// %d B raw -> %d B minified -> %d B gzipped (budget %d KB)."
        % (len(raw), len(mini), len(gz), BUDGET // 1024),
        "// With the Linux-only regions (WEBUI_FULL_GZ, TC002 bundle): %d B minified -> %d B gzipped."
        % (len(full_mini), len(full_gz)),
        "// ETag = MD5 of the gzip stream. SRC-MD5 %s (source-unchanged check)."
        % hashlib.md5(raw).hexdigest(),
        "",
        "#include <pgmspace.h>",
        "",
        "namespace awtrix {",
        "",
    ]
    lines += gz_array("WEBUI", gz)
    lines += ["", "#if defined(%s)" % FULL_GUARD]
    lines += gz_array("WEBUI_FULL", full_gz)
    lines += ["#endif", "", "}  // namespace awtrix", ""]
    return "\n".join(lines)


def build_webui_asset():
    with open(SRC, "rb") as f:
        raw = f.read()
    src_md5 = hashlib.md5(raw).hexdigest()

    if os.path.exists(OUT):
        with open(OUT, "r") as f:
            current = f.read()
        if src_md5 in current and FULL_GUARD in current:
            return

    try:
        text = raw.decode("utf-8")
        embedded = strip_linux_only(text)
        full = strip_linux_only(text, keep_regions=True)
    except MarkerError as e:
        raise SystemExit("webui: webui/index.html %s" % e)
    mini = minify(embedded.encode("utf-8"))
    gz = gzip.compress(mini, compresslevel=9, mtime=0)
    if len(gz) > BUDGET:
        raise SystemExit(
            "webui: gzipped asset is %d B, over the %d KB budget (%d B). "
            "Trim the sources in webui/src/." % (len(gz), BUDGET // 1024, BUDGET)
        )
    full_mini = minify(full.encode("utf-8"))
    full_gz = gzip.compress(full_mini, compresslevel=9, mtime=0)

    with open(OUT, "w") as f:
        f.write(render_header(raw, mini, gz, full_mini, full_gz))
    print(
        "webui: embedded %d B raw -> %d B minified -> %d B gzipped (ETag %s); "
        "full (TC002) %d B minified -> %d B gzipped"
        % (len(raw), len(mini), len(gz), hashlib.md5(gz).hexdigest(), len(full_mini), len(full_gz))
    )


if env is not None:
    sys.path.insert(0, os.path.join(env["PROJECT_DIR"], "scripts"))
    SRC = os.path.join(env["PROJECT_DIR"], "webui", "index.html")
    OUT = os.path.join(env["PROJECT_DIR"], "src", "transport", "http", "WebUiAsset.h")
    refresh_source()
    build_webui_asset()
