#!/usr/bin/env python3
"""Losslessly pack the pinned original Matrix-Fonts plus the AWTRIX NG supplement glyphs."""

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets/fonts/matrix-fonts"
SUPPLEMENT = ROOT / "assets/fonts/awtrix-ng"
OUTPUT = ROOT / "src/media/MatrixFonts.h"
COMPACT_OUTPUT = ROOT / "src/media/MatrixFontsCompact.h"
COMPACT_FONTS = ("MatrixLight6", "MatrixChunky8x6")
PROFILES = ((OUTPUT, None), (COMPACT_OUTPUT, COMPACT_FONTS))


def read_bdf(path):
    glyphs, properties = {}, {}
    current = None
    in_bitmap = False
    for line in path.read_text(encoding="latin-1").splitlines():
        fields = line.split()
        if not fields:
            continue
        key = fields[0]
        if key in ("FONT_ASCENT", "FONT_DESCENT"):
            properties[key] = int(fields[1])
        elif key == "STARTCHAR":
            current = {"rows": []}
        elif key == "ENCODING":
            current["cp"] = int(fields[1])
        elif key == "DWIDTH":
            current["advance"] = int(fields[1])
        elif key == "BBX":
            current["box"] = tuple(map(int, fields[1:]))
        elif key == "BITMAP":
            in_bitmap = True
        elif key == "ENDCHAR":
            if current["cp"] >= 0:
                glyphs[current["cp"]] = current
            current, in_bitmap = None, False
        elif in_bitmap:
            current["rows"].append(line.strip())
    return glyphs, properties


def packed(glyph):
    w, h, _, _ = glyph["box"]
    if len(glyph["rows"]) != h:
        raise ValueError("BDF bitmap height mismatch")
    bits = []
    for row in glyph["rows"]:
        value, span = int(row, 16), len(row) * 4
        bits.extend((value >> (span - 1 - x)) & 1 for x in range(w))
    data = bytearray((len(bits) + 7) // 8)
    for i, bit in enumerate(bits):
        data[i // 8] |= bit << (7 - i % 8)
    return bytes(data)


def rows(values, fmt=str, per_line=16):
    return ["    " + ", ".join(fmt(v) for v in values[i:i + per_line]) + ","
            for i in range(0, len(values), per_line)]


def generate(selected_fonts=None):
    selected = set(selected_fonts) if selected_fonts is not None else None
    manifest = json.loads((SOURCE / "provenance.json").read_text(encoding="utf-8"))
    header = ["#pragma once", "", "// GENERATED by scripts/gen_matrix_fonts.py; do not edit.",
           "// Original glyphs: Trip5 / Matrix-Fonts, commit " + manifest["commit"],
           "// SPDX-License-Identifier: OFL-1.1",
           "// Combined font data: SIL Open Font License 1.1; application and generator licenses unchanged.",
           "// Copyright (c) 2026 Trip5; AWTRIX NG font contributions: Stephan Muehl (Blueforcer).",
           "// Includes BoutiqueBitmap7x7 / MisakiGothic-derived glyphs and retained upstream notices.",
           "// Full font license, MIT/Apache notices and reserved names: LICENSES/MIT-Matrix-Fonts.txt.",
           "// AWTRIX NG glyphs: assets/fonts/awtrix-ng/<font>.bdf, drawn for AWTRIX NG in the style of",
           "// each original font. Per font below: original glyphs, AWTRIX NG glyphs, originals replaced.",
           '#include "core/render/FontCatalog.h"', "", "namespace awtrix {", ""]
    entries, fonts, total = [], [], 0
    blob, offsets = bytearray(), {}
    indices, range_tables = {}, {}
    lookups = []
    for file in manifest["files"]:
        path = SOURCE / file["path"]
        if hashlib.sha256(path.read_bytes()).hexdigest() != file["sha256"]:
            raise ValueError("pinned source hash mismatch: " + file["path"])
        if path.suffix != ".bdf":
            continue
        name = path.stem
        if selected is not None and name not in selected:
            continue
        glyphs, props = read_bdf(path)
        original = len(glyphs)
        added = replaced = 0
        extra_path = SUPPLEMENT / (name + ".bdf")
        if extra_path.exists():
            extra, extra_props = read_bdf(extra_path)
            if extra_props != props:
                raise ValueError(f"{extra_path.name}: ascent/descent differ from the original")
            replaced = len(set(extra) & set(glyphs))
            added = len(extra) - replaced
            glyphs.update(extra)
        if 0xA0 not in glyphs:
            glyphs[0xA0] = glyphs[0x20]
        order = list(range(32, 127)) + sorted(cp for cp in glyphs if not 32 <= cp <= 126)
        table, slots = [], {}
        for cp in order:
            g = glyphs[cp]
            bits = packed(g)
            if bits not in offsets:
                offsets[bits] = len(blob)
                blob.extend(bits)
            w, h, x, y = g["box"]
            if len(blob) > 65535 or not (0 <= w <= 255 and 0 <= h <= 15
                    and 0 <= g["advance"] <= 15 and -128 <= x <= 127
                    and -128 <= -y - h <= 127):
                raise ValueError("font exceeds renderer representation: " + name)
            entry = (offsets[bits], w, h, g["advance"], x, -y - h)
            if cp == 0xA0 and g is glyphs[0x20]:
                slots[cp] = slots[0x20]
                continue
            table.append(entry)
            slots[cp] = len(table)
        # Join nearby codepoints to avoid a pointer-heavy range per isolated symbol.
        ranges = []
        for cp in sorted(cp for cp in glyphs if not 32 <= cp <= 126):
            if ranges and cp - ranges[-1][-1] <= 8:
                ranges[-1].append(cp)
            else:
                ranges.append([cp])
        if len(ranges) > 255:
            raise ValueError("too many sparse ranges: " + name)
        fonts += [f"// {name}: {original} original, {added} AWTRIX NG, {replaced} originals replaced"]
        fonts += [f"inline const FontGlyph k{name}Glyphs[] = {{"]
        fonts += ["    {" + ", ".join(map(str, g)) + "}," for g in table] + ["};"]
        spans = []
        for span in ranges:
            values = tuple(slots.get(cp, 0) for cp in range(span[0], span[-1] + 1))
            if values not in indices:
                ident = f"kMatrixFontIndex{len(indices)}"
                indices[values] = ident
                lookups += [f"inline const uint16_t {ident}[] = {{"]
                lookups += rows(values) + ["};"]
                total += 2 * len(values)
            spans.append((span[0], span[-1], indices[values]))
        spans = tuple(spans)
        if spans not in range_tables:
            ident = f"kMatrixFontRanges{len(range_tables)}"
            range_tables[spans] = ident
            lookups += [f"inline const FontRange {ident}[] = {{"]
            lookups += [f"    {{{first}, {last}, {index}}}," for first, last, index in spans] + ["};"]
            total += 8 * len(spans)
        ascent, descent = props["FONT_ASCENT"], props["FONT_DESCENT"]
        fonts += [f"inline const GfxFont k{name}Font = {{kMatrixFontBitmap, k{name}Glyphs, 32, 126, "
                f"{ascent + descent}, {range_tables[spans]}, {len(ranges)}}};", ""]
        ident = "matrix-" + name.removeprefix("Matrix").lower()
        entries.append((ident, name, ascent, descent))
        total += 6 * len(table)
    total += len(blob)
    if selected is not None and {entry[1] for entry in entries} != selected:
        raise ValueError("unknown font in selected profile")
    out = header
    if selected is None:
        out += ["// Bitmaps of all ten fonts; a glyph two fonts draw alike is stored once."]
    out += ["inline const uint8_t kMatrixFontBitmap[] = {"]
    out += rows(blob, lambda v: f"0x{v:02X}") + ["};", ""] + lookups + [""] + fonts
    out += ["inline constexpr FontEntry kMatrixFontEntries[] = {"]
    out += [f'    {{"{ident}", &k{name}Font, {a}, {d}, {a+d}}},' for ident, name, a, d in entries]
    out += ["};", "", "}", ""]
    return "\n".join(out), total


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for output, selected in PROFILES:
        result, size = generate(selected)
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != result:
                raise SystemExit(f"{output.name} stale; run python scripts/gen_matrix_fonts.py")
        else:
            output.write_text(result, encoding="utf-8", newline="\n")
        print(f"{output.name}: {len(selected) if selected is not None else 10} fonts with AWTRIX NG glyphs, "
              f"estimated 32-bit tables {size} bytes; " + ("in sync" if args.check else "generated"))


if __name__ == "__main__":
    main()
